// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content.proto

package content

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContentCreateRequest_Type int32

const (
	ContentCreateRequest_UNKNOWN ContentCreateRequest_Type = 0
	ContentCreateRequest_PICTURE ContentCreateRequest_Type = 1
	ContentCreateRequest_VIDEO   ContentCreateRequest_Type = 2
)

var ContentCreateRequest_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "PICTURE",
	2: "VIDEO",
}

var ContentCreateRequest_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"PICTURE": 1,
	"VIDEO":   2,
}

func (x ContentCreateRequest_Type) String() string {
	return proto.EnumName(ContentCreateRequest_Type_name, int32(x))
}

func (ContentCreateRequest_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{0, 0}
}

type ContentCreateResponse_Status int32

const (
	ContentCreateResponse_UNKNOWN       ContentCreateResponse_Status = 0
	ContentCreateResponse_INVALID_PARAM ContentCreateResponse_Status = -1
	ContentCreateResponse_SUCCESS       ContentCreateResponse_Status = 1
	ContentCreateResponse_INVALID_TOKEN ContentCreateResponse_Status = 2
)

var ContentCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "INVALID_TOKEN",
}

var ContentCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"INVALID_TOKEN": 2,
}

func (x ContentCreateResponse_Status) String() string {
	return proto.EnumName(ContentCreateResponse_Status_name, int32(x))
}

func (ContentCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{1, 0}
}

type ContentDeleteResponse_Status int32

const (
	ContentDeleteResponse_UNKNOWN       ContentDeleteResponse_Status = 0
	ContentDeleteResponse_INVALID_PARAM ContentDeleteResponse_Status = -1
	ContentDeleteResponse_SUCCESS       ContentDeleteResponse_Status = 1
	ContentDeleteResponse_INVALID_TOKEN ContentDeleteResponse_Status = 2
)

var ContentDeleteResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "INVALID_TOKEN",
}

var ContentDeleteResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"INVALID_TOKEN": 2,
}

func (x ContentDeleteResponse_Status) String() string {
	return proto.EnumName(ContentDeleteResponse_Status_name, int32(x))
}

func (ContentDeleteResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{3, 0}
}

type ContentCreateRequest struct {
	ContentId            string                    `protobuf:"bytes,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	ContentToken         string                    `protobuf:"bytes,2,opt,name=contentToken,proto3" json:"contentToken,omitempty"`
	Content              []byte                    `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Type                 ContentCreateRequest_Type `protobuf:"varint,4,opt,name=type,proto3,enum=ContentCreateRequest_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *ContentCreateRequest) Reset()         { *m = ContentCreateRequest{} }
func (m *ContentCreateRequest) String() string { return proto.CompactTextString(m) }
func (*ContentCreateRequest) ProtoMessage()    {}
func (*ContentCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{0}
}

func (m *ContentCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentCreateRequest.Unmarshal(m, b)
}
func (m *ContentCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentCreateRequest.Marshal(b, m, deterministic)
}
func (m *ContentCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentCreateRequest.Merge(m, src)
}
func (m *ContentCreateRequest) XXX_Size() int {
	return xxx_messageInfo_ContentCreateRequest.Size(m)
}
func (m *ContentCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContentCreateRequest proto.InternalMessageInfo

func (m *ContentCreateRequest) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *ContentCreateRequest) GetContentToken() string {
	if m != nil {
		return m.ContentToken
	}
	return ""
}

func (m *ContentCreateRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *ContentCreateRequest) GetType() ContentCreateRequest_Type {
	if m != nil {
		return m.Type
	}
	return ContentCreateRequest_UNKNOWN
}

type ContentCreateResponse struct {
	Status               ContentCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ContentCreateResponse_Status" json:"status,omitempty"`
	ContentId            string                       `protobuf:"bytes,2,opt,name=contentId,proto3" json:"contentId,omitempty"`
	ContentToken         string                       `protobuf:"bytes,3,opt,name=contentToken,proto3" json:"contentToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ContentCreateResponse) Reset()         { *m = ContentCreateResponse{} }
func (m *ContentCreateResponse) String() string { return proto.CompactTextString(m) }
func (*ContentCreateResponse) ProtoMessage()    {}
func (*ContentCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{1}
}

func (m *ContentCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentCreateResponse.Unmarshal(m, b)
}
func (m *ContentCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentCreateResponse.Marshal(b, m, deterministic)
}
func (m *ContentCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentCreateResponse.Merge(m, src)
}
func (m *ContentCreateResponse) XXX_Size() int {
	return xxx_messageInfo_ContentCreateResponse.Size(m)
}
func (m *ContentCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContentCreateResponse proto.InternalMessageInfo

func (m *ContentCreateResponse) GetStatus() ContentCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return ContentCreateResponse_UNKNOWN
}

func (m *ContentCreateResponse) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *ContentCreateResponse) GetContentToken() string {
	if m != nil {
		return m.ContentToken
	}
	return ""
}

type ContentDeleteRequest struct {
	ContentId            string   `protobuf:"bytes,1,opt,name=contentId,proto3" json:"contentId,omitempty"`
	ContentToken         string   `protobuf:"bytes,2,opt,name=contentToken,proto3" json:"contentToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContentDeleteRequest) Reset()         { *m = ContentDeleteRequest{} }
func (m *ContentDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*ContentDeleteRequest) ProtoMessage()    {}
func (*ContentDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{2}
}

func (m *ContentDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentDeleteRequest.Unmarshal(m, b)
}
func (m *ContentDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentDeleteRequest.Marshal(b, m, deterministic)
}
func (m *ContentDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentDeleteRequest.Merge(m, src)
}
func (m *ContentDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_ContentDeleteRequest.Size(m)
}
func (m *ContentDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContentDeleteRequest proto.InternalMessageInfo

func (m *ContentDeleteRequest) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *ContentDeleteRequest) GetContentToken() string {
	if m != nil {
		return m.ContentToken
	}
	return ""
}

type ContentDeleteResponse struct {
	Status               ContentDeleteResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=ContentDeleteResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *ContentDeleteResponse) Reset()         { *m = ContentDeleteResponse{} }
func (m *ContentDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*ContentDeleteResponse) ProtoMessage()    {}
func (*ContentDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_61cc9617ce0cf609, []int{3}
}

func (m *ContentDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContentDeleteResponse.Unmarshal(m, b)
}
func (m *ContentDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContentDeleteResponse.Marshal(b, m, deterministic)
}
func (m *ContentDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContentDeleteResponse.Merge(m, src)
}
func (m *ContentDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_ContentDeleteResponse.Size(m)
}
func (m *ContentDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContentDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContentDeleteResponse proto.InternalMessageInfo

func (m *ContentDeleteResponse) GetStatus() ContentDeleteResponse_Status {
	if m != nil {
		return m.Status
	}
	return ContentDeleteResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("ContentCreateRequest_Type", ContentCreateRequest_Type_name, ContentCreateRequest_Type_value)
	proto.RegisterEnum("ContentCreateResponse_Status", ContentCreateResponse_Status_name, ContentCreateResponse_Status_value)
	proto.RegisterEnum("ContentDeleteResponse_Status", ContentDeleteResponse_Status_name, ContentDeleteResponse_Status_value)
	proto.RegisterType((*ContentCreateRequest)(nil), "ContentCreateRequest")
	proto.RegisterType((*ContentCreateResponse)(nil), "ContentCreateResponse")
	proto.RegisterType((*ContentDeleteRequest)(nil), "ContentDeleteRequest")
	proto.RegisterType((*ContentDeleteResponse)(nil), "ContentDeleteResponse")
}

func init() { proto.RegisterFile("content.proto", fileDescriptor_61cc9617ce0cf609) }

var fileDescriptor_61cc9617ce0cf609 = []byte{
	// 341 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xdd, 0xb4, 0xa6, 0x74, 0x6c, 0xcb, 0xba, 0x58, 0x09, 0x45, 0xa1, 0xec, 0xa9, 0x20,
	0xec, 0xa1, 0x22, 0x9e, 0x4b, 0x9a, 0x43, 0xa8, 0x26, 0x75, 0x93, 0x54, 0x6f, 0x52, 0x75, 0x4f,
	0x4a, 0x12, 0x9b, 0xed, 0xa1, 0xf8, 0x34, 0x3e, 0x91, 0x0f, 0xe1, 0x83, 0x28, 0xf9, 0x67, 0xd8,
	0x1a, 0xe8, 0x45, 0x73, 0xfb, 0x86, 0xdf, 0x4c, 0x66, 0xbe, 0x2f, 0x81, 0xee, 0x63, 0x14, 0x4a,
	0x11, 0x4a, 0x16, 0xaf, 0x22, 0x19, 0xd1, 0x0f, 0x04, 0x47, 0x66, 0x5e, 0x31, 0x57, 0x62, 0x29,
	0x05, 0x17, 0xaf, 0x6b, 0x91, 0x48, 0x72, 0x02, 0xed, 0x82, 0xb4, 0x9f, 0x0c, 0x34, 0x44, 0xa3,
	0x36, 0xaf, 0x0a, 0x84, 0x42, 0xa7, 0x10, 0x7e, 0xf4, 0x2c, 0x42, 0x43, 0xcb, 0x00, 0xa5, 0x46,
	0x0c, 0x68, 0x15, 0xda, 0x68, 0x0c, 0xd1, 0xa8, 0xc3, 0x4b, 0x49, 0x18, 0x34, 0xe5, 0x26, 0x16,
	0x46, 0x73, 0x88, 0x46, 0xbd, 0xf1, 0x80, 0xd5, 0x2d, 0xc0, 0xfc, 0x4d, 0x2c, 0x78, 0xc6, 0xd1,
	0x33, 0x68, 0xa6, 0x8a, 0x1c, 0x40, 0x2b, 0x70, 0x66, 0x8e, 0x7b, 0xeb, 0xe0, 0xbd, 0x54, 0xcc,
	0x6d, 0xd3, 0x0f, 0xb8, 0x85, 0x11, 0x69, 0xc3, 0xfe, 0xc2, 0x9e, 0x5a, 0x2e, 0xd6, 0xe8, 0x27,
	0x82, 0xfe, 0xd6, 0xc0, 0x24, 0x8e, 0xc2, 0x44, 0x90, 0x0b, 0xd0, 0x13, 0xb9, 0x94, 0xeb, 0x24,
	0xbb, 0xa7, 0x37, 0x3e, 0x65, 0xb5, 0x1c, 0xf3, 0x32, 0x88, 0x17, 0xb0, 0xea, 0x84, 0xb6, 0xcb,
	0x89, 0xc6, 0x6f, 0x27, 0xe8, 0x0d, 0xe8, 0xf9, 0x4c, 0xf5, 0x82, 0x01, 0x74, 0x6d, 0x67, 0x31,
	0xb9, 0xb2, 0xa7, 0xf7, 0xf3, 0x09, 0x9f, 0x5c, 0xe3, 0xaf, 0xf2, 0x41, 0x29, 0xe8, 0x05, 0xa6,
	0x69, 0x79, 0x1e, 0x46, 0xe4, 0xb0, 0x02, 0x7d, 0x77, 0x66, 0x39, 0x58, 0xa3, 0x77, 0x3f, 0xb1,
	0x4d, 0xc5, 0x8b, 0xf8, 0xc3, 0xd8, 0xe8, 0x7b, 0xe5, 0x5f, 0x39, 0x7a, 0x97, 0x7f, 0x2a, 0xb7,
	0xe5, 0xdf, 0x3f, 0x5c, 0x3f, 0x7e, 0x83, 0x56, 0xf1, 0x6a, 0x72, 0x09, 0x7a, 0x1e, 0x1f, 0xe9,
	0xd7, 0x7e, 0x47, 0x83, 0xe3, 0xfa, 0x94, 0xd3, 0xc6, 0x7c, 0xef, 0xaa, 0x51, 0xb1, 0xb2, 0x6a,
	0x54, 0xcf, 0x7b, 0xd0, 0xb3, 0x3f, 0xe7, 0xfc, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x92, 0x6a, 0xa8,
	0x32, 0x4a, 0x03, 0x00, 0x00,
}
