// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCreateResponse_Status int32

const (
	UserCreateResponse_UNKNOWN     UserCreateResponse_Status = 0
	UserCreateResponse_EMPTY_PARAM UserCreateResponse_Status = -1
	UserCreateResponse_SUCCESS     UserCreateResponse_Status = 1
	UserCreateResponse_USER_EXIST  UserCreateResponse_Status = 2
)

var UserCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "EMPTY_PARAM",
	1:  "SUCCESS",
	2:  "USER_EXIST",
}

var UserCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":     0,
	"EMPTY_PARAM": -1,
	"SUCCESS":     1,
	"USER_EXIST":  2,
}

func (x UserCreateResponse_Status) String() string {
	return proto.EnumName(UserCreateResponse_Status_name, int32(x))
}

func (UserCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0}
}

type UserCreateRequest struct {
	StudentId            string   `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	StudentName          string   `protobuf:"bytes,2,opt,name=studentName,proto3" json:"studentName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

func (m *UserCreateRequest) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

type UserCreateResponse struct {
	Status               UserCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=UserCreateResponse_Status" json:"status,omitempty"`
	UserId               int32                     `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UserCreateResponse) Reset()         { *m = UserCreateResponse{} }
func (m *UserCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UserCreateResponse) ProtoMessage()    {}
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateResponse.Unmarshal(m, b)
}
func (m *UserCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateResponse.Marshal(b, m, deterministic)
}
func (m *UserCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateResponse.Merge(m, src)
}
func (m *UserCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UserCreateResponse.Size(m)
}
func (m *UserCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateResponse proto.InternalMessageInfo

func (m *UserCreateResponse) GetStatus() UserCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return UserCreateResponse_UNKNOWN
}

func (m *UserCreateResponse) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func init() {
	proto.RegisterEnum("UserCreateResponse_Status", UserCreateResponse_Status_name, UserCreateResponse_Status_value)
	proto.RegisterType((*UserCreateRequest)(nil), "UserCreateRequest")
	proto.RegisterType((*UserCreateResponse)(nil), "UserCreateResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x86, 0xbb, 0x45, 0x57, 0x3a, 0x81, 0x12, 0x47, 0x90, 0x50, 0x3c, 0x94, 0x9c, 0x3c, 0xe5,
	0x90, 0x1e, 0x3d, 0x95, 0x90, 0x43, 0xd0, 0xc6, 0xb2, 0xdb, 0x45, 0x3d, 0x95, 0x48, 0xe6, 0x68,
	0x53, 0x77, 0x76, 0x5f, 0xcb, 0x57, 0x54, 0xb2, 0x8d, 0x58, 0x88, 0x7b, 0x9b, 0xd9, 0x8f, 0x7f,
	0x3e, 0x7e, 0x00, 0xcf, 0x64, 0xb3, 0xa3, 0xed, 0x5c, 0x97, 0x6a, 0xb8, 0x36, 0x4c, 0xb6, 0xb0,
	0xd4, 0x38, 0x52, 0xf4, 0xe9, 0x89, 0x1d, 0xde, 0xc1, 0x8c, 0x9d, 0x6f, 0xe9, 0xe0, 0xaa, 0x36,
	0x11, 0x4b, 0x71, 0x3f, 0x53, 0x7f, 0x0b, 0x5c, 0x42, 0x34, 0x0c, 0x75, 0xf3, 0x41, 0xc9, 0x34,
	0xfc, 0x9f, 0xaf, 0xd2, 0x2f, 0x01, 0x78, 0x9e, 0xca, 0xc7, 0xee, 0xc0, 0x84, 0x39, 0x48, 0x76,
	0x8d, 0xf3, 0x1c, 0x32, 0xe7, 0xf9, 0x22, 0x1b, 0x43, 0x99, 0x0e, 0x84, 0x1a, 0x48, 0xbc, 0x05,
	0xd9, 0xdb, 0x56, 0x6d, 0xb8, 0x73, 0xa9, 0x86, 0x29, 0x7d, 0x02, 0x79, 0x22, 0x31, 0x82, 0x2b,
	0x53, 0x3f, 0xd6, 0xcf, 0x2f, 0x75, 0x3c, 0xc1, 0x04, 0xa2, 0x72, 0xb3, 0xdd, 0xbd, 0xed, 0xb7,
	0x6b, 0xb5, 0xde, 0xc4, 0xdf, 0xbf, 0x4f, 0xf4, 0x98, 0x36, 0x45, 0x51, 0x6a, 0x1d, 0x0b, 0x9c,
	0x03, 0x18, 0x5d, 0xaa, 0x7d, 0xf9, 0x5a, 0xe9, 0x5d, 0x3c, 0xcd, 0x1f, 0xe0, 0xa2, 0x57, 0xc1,
	0x15, 0xc8, 0x93, 0x0e, 0x62, 0x36, 0xaa, 0x65, 0x71, 0xf3, 0x8f, 0x6f, 0x3a, 0x79, 0x97, 0xa1,
	0xc9, 0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xba, 0x85, 0x82, 0x1c, 0x57, 0x01, 0x00, 0x00,
}
