// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserCreateResponse_Status int32

const (
	UserCreateResponse_UNKNOWN       UserCreateResponse_Status = 0
	UserCreateResponse_INVALID_PARAM UserCreateResponse_Status = -1
	UserCreateResponse_SUCCESS       UserCreateResponse_Status = 1
	UserCreateResponse_USER_EXIST    UserCreateResponse_Status = 2
)

var UserCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "USER_EXIST",
}

var UserCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"USER_EXIST":    2,
}

func (x UserCreateResponse_Status) String() string {
	return proto.EnumName(UserCreateResponse_Status_name, int32(x))
}

func (UserCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1, 0}
}

type UserInfo_Status int32

const (
	UserInfo_UNKNOWN UserInfo_Status = 0
	UserInfo_NORMAL  UserInfo_Status = 1
	UserInfo_FROZEN  UserInfo_Status = 2
)

var UserInfo_Status_name = map[int32]string{
	0: "UNKNOWN",
	1: "NORMAL",
	2: "FROZEN",
}

var UserInfo_Status_value = map[string]int32{
	"UNKNOWN": 0,
	"NORMAL":  1,
	"FROZEN":  2,
}

func (x UserInfo_Status) String() string {
	return proto.EnumName(UserInfo_Status_name, int32(x))
}

func (UserInfo_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3, 0}
}

type UserInfo_Role int32

const (
	UserInfo_ROLE_UNKNOWN UserInfo_Role = 0
	UserInfo_USER         UserInfo_Role = 1
	UserInfo_ADMIN        UserInfo_Role = 2
)

var UserInfo_Role_name = map[int32]string{
	0: "ROLE_UNKNOWN",
	1: "USER",
	2: "ADMIN",
}

var UserInfo_Role_value = map[string]int32{
	"ROLE_UNKNOWN": 0,
	"USER":         1,
	"ADMIN":        2,
}

func (x UserInfo_Role) String() string {
	return proto.EnumName(UserInfo_Role_name, int32(x))
}

func (UserInfo_Role) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3, 1}
}

type UserUpdateResponse_Status int32

const (
	UserUpdateResponse_UNKNOWN       UserUpdateResponse_Status = 0
	UserUpdateResponse_INVALID_PARAM UserUpdateResponse_Status = -1
	UserUpdateResponse_SUCCESS       UserUpdateResponse_Status = 1
	UserUpdateResponse_NOT_FOUND     UserUpdateResponse_Status = 2
)

var UserUpdateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "NOT_FOUND",
}

var UserUpdateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"NOT_FOUND":     2,
}

func (x UserUpdateResponse_Status) String() string {
	return proto.EnumName(UserUpdateResponse_Status_name, int32(x))
}

func (UserUpdateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6, 0}
}

type AvatarCreateResponse_Status int32

const (
	AvatarCreateResponse_UNKNOWN       AvatarCreateResponse_Status = 0
	AvatarCreateResponse_INVALID_PARAM AvatarCreateResponse_Status = -1
	AvatarCreateResponse_SUCCESS       AvatarCreateResponse_Status = 1
	AvatarCreateResponse_NOT_FOUND     AvatarCreateResponse_Status = 2
)

var AvatarCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "NOT_FOUND",
}

var AvatarCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"NOT_FOUND":     2,
}

func (x AvatarCreateResponse_Status) String() string {
	return proto.EnumName(AvatarCreateResponse_Status_name, int32(x))
}

func (AvatarCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8, 0}
}

type UserCreateRequest struct {
	StudentId            string   `protobuf:"bytes,1,opt,name=studentId,proto3" json:"studentId,omitempty"`
	StudentName          string   `protobuf:"bytes,2,opt,name=studentName,proto3" json:"studentName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserCreateRequest) Reset()         { *m = UserCreateRequest{} }
func (m *UserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*UserCreateRequest) ProtoMessage()    {}
func (*UserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *UserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateRequest.Unmarshal(m, b)
}
func (m *UserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateRequest.Marshal(b, m, deterministic)
}
func (m *UserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateRequest.Merge(m, src)
}
func (m *UserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_UserCreateRequest.Size(m)
}
func (m *UserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateRequest proto.InternalMessageInfo

func (m *UserCreateRequest) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

func (m *UserCreateRequest) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

type UserCreateResponse struct {
	Status               UserCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=UserCreateResponse_Status" json:"status,omitempty"`
	User                 *UserInfo                 `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UserCreateResponse) Reset()         { *m = UserCreateResponse{} }
func (m *UserCreateResponse) String() string { return proto.CompactTextString(m) }
func (*UserCreateResponse) ProtoMessage()    {}
func (*UserCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserCreateResponse.Unmarshal(m, b)
}
func (m *UserCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserCreateResponse.Marshal(b, m, deterministic)
}
func (m *UserCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserCreateResponse.Merge(m, src)
}
func (m *UserCreateResponse) XXX_Size() int {
	return xxx_messageInfo_UserCreateResponse.Size(m)
}
func (m *UserCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserCreateResponse proto.InternalMessageInfo

func (m *UserCreateResponse) GetStatus() UserCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return UserCreateResponse_UNKNOWN
}

func (m *UserCreateResponse) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UserQueryRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserQueryRequest) Reset()         { *m = UserQueryRequest{} }
func (m *UserQueryRequest) String() string { return proto.CompactTextString(m) }
func (*UserQueryRequest) ProtoMessage()    {}
func (*UserQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *UserQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserQueryRequest.Unmarshal(m, b)
}
func (m *UserQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserQueryRequest.Marshal(b, m, deterministic)
}
func (m *UserQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserQueryRequest.Merge(m, src)
}
func (m *UserQueryRequest) XXX_Size() int {
	return xxx_messageInfo_UserQueryRequest.Size(m)
}
func (m *UserQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserQueryRequest proto.InternalMessageInfo

func (m *UserQueryRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type UserInfo struct {
	UserId               int32           `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	UserName             string          `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	AvatarId             string          `protobuf:"bytes,3,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	Telephone            string          `protobuf:"bytes,4,opt,name=telephone,proto3" json:"telephone,omitempty"`
	StudentId            string          `protobuf:"bytes,5,opt,name=studentId,proto3" json:"studentId,omitempty"`
	StudentName          string          `protobuf:"bytes,6,opt,name=studentName,proto3" json:"studentName,omitempty"`
	Status               UserInfo_Status `protobuf:"varint,7,opt,name=status,proto3,enum=UserInfo_Status" json:"status,omitempty"`
	Role                 UserInfo_Role   `protobuf:"varint,8,opt,name=role,proto3,enum=UserInfo_Role" json:"role,omitempty"`
	ClearEmpty           bool            `protobuf:"varint,99,opt,name=clearEmpty,proto3" json:"clearEmpty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *UserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInfo) GetAvatarId() string {
	if m != nil {
		return m.AvatarId
	}
	return ""
}

func (m *UserInfo) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

func (m *UserInfo) GetStudentId() string {
	if m != nil {
		return m.StudentId
	}
	return ""
}

func (m *UserInfo) GetStudentName() string {
	if m != nil {
		return m.StudentName
	}
	return ""
}

func (m *UserInfo) GetStatus() UserInfo_Status {
	if m != nil {
		return m.Status
	}
	return UserInfo_UNKNOWN
}

func (m *UserInfo) GetRole() UserInfo_Role {
	if m != nil {
		return m.Role
	}
	return UserInfo_ROLE_UNKNOWN
}

func (m *UserInfo) GetClearEmpty() bool {
	if m != nil {
		return m.ClearEmpty
	}
	return false
}

type UserFindRequest struct {
	UserName             string   `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFindRequest) Reset()         { *m = UserFindRequest{} }
func (m *UserFindRequest) String() string { return proto.CompactTextString(m) }
func (*UserFindRequest) ProtoMessage()    {}
func (*UserFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *UserFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFindRequest.Unmarshal(m, b)
}
func (m *UserFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFindRequest.Marshal(b, m, deterministic)
}
func (m *UserFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFindRequest.Merge(m, src)
}
func (m *UserFindRequest) XXX_Size() int {
	return xxx_messageInfo_UserFindRequest.Size(m)
}
func (m *UserFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserFindRequest proto.InternalMessageInfo

func (m *UserFindRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserFindRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *UserFindRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type UserFindResponse struct {
	User                 []*UserInfo `protobuf:"bytes,1,rep,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UserFindResponse) Reset()         { *m = UserFindResponse{} }
func (m *UserFindResponse) String() string { return proto.CompactTextString(m) }
func (*UserFindResponse) ProtoMessage()    {}
func (*UserFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *UserFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFindResponse.Unmarshal(m, b)
}
func (m *UserFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFindResponse.Marshal(b, m, deterministic)
}
func (m *UserFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFindResponse.Merge(m, src)
}
func (m *UserFindResponse) XXX_Size() int {
	return xxx_messageInfo_UserFindResponse.Size(m)
}
func (m *UserFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserFindResponse proto.InternalMessageInfo

func (m *UserFindResponse) GetUser() []*UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

type UserUpdateResponse struct {
	Status               UserUpdateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=UserUpdateResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *UserUpdateResponse) Reset()         { *m = UserUpdateResponse{} }
func (m *UserUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UserUpdateResponse) ProtoMessage()    {}
func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateResponse.Unmarshal(m, b)
}
func (m *UserUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateResponse.Marshal(b, m, deterministic)
}
func (m *UserUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateResponse.Merge(m, src)
}
func (m *UserUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UserUpdateResponse.Size(m)
}
func (m *UserUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateResponse proto.InternalMessageInfo

func (m *UserUpdateResponse) GetStatus() UserUpdateResponse_Status {
	if m != nil {
		return m.Status
	}
	return UserUpdateResponse_UNKNOWN
}

type AvatarCreateRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Content              []byte   `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarCreateRequest) Reset()         { *m = AvatarCreateRequest{} }
func (m *AvatarCreateRequest) String() string { return proto.CompactTextString(m) }
func (*AvatarCreateRequest) ProtoMessage()    {}
func (*AvatarCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *AvatarCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarCreateRequest.Unmarshal(m, b)
}
func (m *AvatarCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarCreateRequest.Marshal(b, m, deterministic)
}
func (m *AvatarCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarCreateRequest.Merge(m, src)
}
func (m *AvatarCreateRequest) XXX_Size() int {
	return xxx_messageInfo_AvatarCreateRequest.Size(m)
}
func (m *AvatarCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarCreateRequest proto.InternalMessageInfo

func (m *AvatarCreateRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *AvatarCreateRequest) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type AvatarCreateResponse struct {
	Status               AvatarCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=AvatarCreateResponse_Status" json:"status,omitempty"`
	AvatarId             string                      `protobuf:"bytes,2,opt,name=avatarId,proto3" json:"avatarId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AvatarCreateResponse) Reset()         { *m = AvatarCreateResponse{} }
func (m *AvatarCreateResponse) String() string { return proto.CompactTextString(m) }
func (*AvatarCreateResponse) ProtoMessage()    {}
func (*AvatarCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *AvatarCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarCreateResponse.Unmarshal(m, b)
}
func (m *AvatarCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarCreateResponse.Marshal(b, m, deterministic)
}
func (m *AvatarCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarCreateResponse.Merge(m, src)
}
func (m *AvatarCreateResponse) XXX_Size() int {
	return xxx_messageInfo_AvatarCreateResponse.Size(m)
}
func (m *AvatarCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarCreateResponse proto.InternalMessageInfo

func (m *AvatarCreateResponse) GetStatus() AvatarCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return AvatarCreateResponse_UNKNOWN
}

func (m *AvatarCreateResponse) GetAvatarId() string {
	if m != nil {
		return m.AvatarId
	}
	return ""
}

func init() {
	proto.RegisterEnum("UserCreateResponse_Status", UserCreateResponse_Status_name, UserCreateResponse_Status_value)
	proto.RegisterEnum("UserInfo_Status", UserInfo_Status_name, UserInfo_Status_value)
	proto.RegisterEnum("UserInfo_Role", UserInfo_Role_name, UserInfo_Role_value)
	proto.RegisterEnum("UserUpdateResponse_Status", UserUpdateResponse_Status_name, UserUpdateResponse_Status_value)
	proto.RegisterEnum("AvatarCreateResponse_Status", AvatarCreateResponse_Status_name, AvatarCreateResponse_Status_value)
	proto.RegisterType((*UserCreateRequest)(nil), "UserCreateRequest")
	proto.RegisterType((*UserCreateResponse)(nil), "UserCreateResponse")
	proto.RegisterType((*UserQueryRequest)(nil), "UserQueryRequest")
	proto.RegisterType((*UserInfo)(nil), "UserInfo")
	proto.RegisterType((*UserFindRequest)(nil), "UserFindRequest")
	proto.RegisterType((*UserFindResponse)(nil), "UserFindResponse")
	proto.RegisterType((*UserUpdateResponse)(nil), "UserUpdateResponse")
	proto.RegisterType((*AvatarCreateRequest)(nil), "AvatarCreateRequest")
	proto.RegisterType((*AvatarCreateResponse)(nil), "AvatarCreateResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 622 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x51, 0x8f, 0xd2, 0x40,
	0x10, 0xb6, 0x5c, 0xe9, 0xc1, 0xdc, 0x71, 0x96, 0x3d, 0x34, 0x4d, 0x73, 0x1a, 0xd2, 0xc4, 0x84,
	0x68, 0xae, 0xc9, 0xa1, 0x3e, 0x9b, 0x06, 0x8a, 0x69, 0x84, 0x56, 0xb7, 0x57, 0x35, 0xfa, 0x40,
	0x2a, 0x2c, 0x91, 0x04, 0x5a, 0x6c, 0x17, 0x93, 0x7b, 0xf7, 0x3f, 0xf8, 0x53, 0xee, 0xe7, 0x69,
	0x76, 0xdb, 0x42, 0x5b, 0x7a, 0xb9, 0x07, 0xe5, 0x89, 0x99, 0xfd, 0x76, 0x76, 0xfa, 0x7d, 0xdf,
	0x0c, 0xc0, 0x36, 0x26, 0x91, 0xbe, 0x89, 0x42, 0x1a, 0x6a, 0x2e, 0xb4, 0xbd, 0x98, 0x44, 0x83,
	0x88, 0xf8, 0x94, 0x60, 0xf2, 0x63, 0x4b, 0x62, 0x8a, 0x2e, 0xa0, 0x19, 0xd3, 0xed, 0x9c, 0x04,
	0xd4, 0x9a, 0x2b, 0x42, 0x57, 0xe8, 0x35, 0xf1, 0x3e, 0x81, 0xba, 0x70, 0x92, 0x06, 0xb6, 0xbf,
	0x26, 0x4a, 0x8d, 0x9f, 0xe7, 0x53, 0xda, 0xad, 0x00, 0x28, 0x5f, 0x35, 0xde, 0x84, 0x41, 0x4c,
	0x50, 0x1f, 0xa4, 0x98, 0xfa, 0x74, 0x1b, 0xf3, 0x9a, 0x67, 0x7d, 0x55, 0x3f, 0x04, 0xe9, 0x2e,
	0x47, 0xe0, 0x14, 0x89, 0x9e, 0x80, 0xc8, 0xba, 0xe5, 0xaf, 0x9c, 0xf4, 0x9b, 0xfc, 0x86, 0x15,
	0x2c, 0x42, 0xcc, 0xd3, 0x9a, 0x0d, 0x52, 0x72, 0x01, 0x9d, 0xc0, 0xb1, 0x67, 0xbf, 0xb3, 0x9d,
	0x4f, 0xb6, 0xfc, 0x00, 0xa9, 0xd0, 0xb2, 0xec, 0x8f, 0xc6, 0xd8, 0x1a, 0x4e, 0xdf, 0x1b, 0xd8,
	0x98, 0xc8, 0x7f, 0xb2, 0x9f, 0xc0, 0x80, 0xae, 0x37, 0x18, 0x98, 0xae, 0x2b, 0x0b, 0xe8, 0x0c,
	0xc0, 0x73, 0x4d, 0x3c, 0x35, 0x3f, 0x5b, 0xee, 0xb5, 0x5c, 0xd3, 0x9e, 0x83, 0xcc, 0x5e, 0xf8,
	0xb0, 0x25, 0xd1, 0x4d, 0xc6, 0xc6, 0x63, 0x90, 0xd8, 0x5b, 0x29, 0x15, 0x75, 0x9c, 0x46, 0xda,
	0xaf, 0x23, 0x68, 0x64, 0xed, 0xdc, 0x05, 0x42, 0x2a, 0x34, 0xd8, 0xbf, 0x1c, 0x53, 0xbb, 0x98,
	0x9d, 0xf9, 0x3f, 0x7d, 0xea, 0xb3, 0x5b, 0x47, 0xc9, 0x59, 0x16, 0x33, 0x09, 0x28, 0x59, 0x91,
	0xcd, 0xf7, 0x30, 0x20, 0x8a, 0x98, 0x48, 0xb0, 0x4b, 0x14, 0x05, 0xaa, 0xdf, 0x23, 0x90, 0x74,
	0x20, 0x10, 0xea, 0xed, 0x94, 0x38, 0xe6, 0x4a, 0xc8, 0x3b, 0x5e, 0xcb, 0xfc, 0x6b, 0x20, 0x46,
	0xe1, 0x8a, 0x28, 0x0d, 0x8e, 0x3b, 0xdb, 0xe3, 0x70, 0xb8, 0x22, 0x98, 0x9f, 0xa1, 0xa7, 0x00,
	0xb3, 0x15, 0xf1, 0x23, 0x73, 0xbd, 0xa1, 0x37, 0xca, 0xac, 0x2b, 0xf4, 0x1a, 0x38, 0x97, 0xd1,
	0x2e, 0xab, 0x45, 0x02, 0x90, 0x6c, 0x07, 0x4f, 0x8c, 0xb1, 0x2c, 0xb0, 0xff, 0x23, 0xec, 0x7c,
	0x31, 0x6d, 0xb9, 0xa6, 0x5d, 0x82, 0xc8, 0x8a, 0x23, 0x19, 0x4e, 0xb1, 0x33, 0x36, 0xa7, 0xfb,
	0x1b, 0x0d, 0x10, 0x99, 0x5a, 0xb2, 0x80, 0x9a, 0x50, 0x37, 0x86, 0x13, 0x8b, 0xc1, 0xbf, 0xc2,
	0x43, 0xd6, 0xd4, 0x68, 0x19, 0xcc, 0x33, 0xc5, 0xf2, 0xa4, 0x0b, 0x25, 0xd2, 0x3b, 0x50, 0x5f,
	0x2d, 0xd7, 0x4b, 0xca, 0xd5, 0x68, 0xe1, 0x24, 0x60, 0xf2, 0x85, 0x8b, 0x45, 0x4c, 0x28, 0x17,
	0xa2, 0x85, 0xd3, 0x48, 0xbb, 0x4a, 0xfc, 0x90, 0x14, 0x4f, 0x6d, 0x9c, 0x59, 0x52, 0xe8, 0x1e,
	0x55, 0x59, 0xf2, 0x77, 0x6a, 0x7e, 0x6f, 0x33, 0xbf, 0xdf, 0xfc, 0x45, 0x50, 0x89, 0x7c, 0x6d,
	0xf2, 0x8f, 0xee, 0x6e, 0x41, 0xd3, 0x76, 0xae, 0xa7, 0x23, 0xc7, 0xb3, 0x87, 0x72, 0x4d, 0x7b,
	0x0b, 0xe7, 0x06, 0xf7, 0x57, 0x71, 0xda, 0xef, 0xb2, 0xae, 0x02, 0xc7, 0xb3, 0x30, 0xa0, 0x24,
	0x48, 0xb8, 0x3a, 0xc5, 0x59, 0xc8, 0xe6, 0xbb, 0x53, 0xac, 0x94, 0x7e, 0xe4, 0xab, 0xd2, 0x47,
	0x5e, 0xe8, 0x55, 0xb0, 0xb2, 0xc7, 0xf2, 0x73, 0x50, 0x2b, 0xce, 0xc1, 0x7f, 0xa6, 0xa0, 0x7f,
	0x2b, 0x80, 0xc8, 0x78, 0x47, 0x57, 0x20, 0x25, 0x4d, 0x21, 0xa4, 0x1f, 0x2c, 0x40, 0xf5, 0xbc,
	0x62, 0x33, 0xa1, 0x67, 0x50, 0xe7, 0x7b, 0x01, 0xb5, 0xf5, 0xf2, 0x8e, 0x50, 0xf7, 0x2e, 0x40,
	0x2f, 0x40, 0x64, 0x76, 0x41, 0xc9, 0x4c, 0xe5, 0x6c, 0xa9, 0xb6, 0xf5, 0x03, 0x2f, 0xf5, 0x40,
	0x4a, 0x2c, 0x80, 0xf6, 0x15, 0xd2, 0xd7, 0x8b, 0xd6, 0xe8, 0xbf, 0x01, 0x29, 0xe1, 0x12, 0xbd,
	0xde, 0xb5, 0xde, 0xd1, 0x2b, 0xf4, 0x54, 0x1f, 0x55, 0x92, 0xfe, 0x4d, 0xe2, 0x0b, 0xff, 0xe5,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xce, 0x6d, 0xf3, 0x87, 0xfe, 0x05, 0x00, 0x00,
}
