// Code generated by protoc-gen-go. DO NOT EDIT.
// source: file.proto

package file

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FileDeleteResponse_Status int32

const (
	FileDeleteResponse_UNKNOWN       FileDeleteResponse_Status = 0
	FileDeleteResponse_INVALID_PARAM FileDeleteResponse_Status = -1
	FileDeleteResponse_SUCCESS       FileDeleteResponse_Status = 1
	FileDeleteResponse_NOT_FOUND     FileDeleteResponse_Status = 2
)

var FileDeleteResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "NOT_FOUND",
}

var FileDeleteResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"NOT_FOUND":     2,
}

func (x FileDeleteResponse_Status) String() string {
	return proto.EnumName(FileDeleteResponse_Status_name, int32(x))
}

func (FileDeleteResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1, 0}
}

type FileQueryResponse_Status int32

const (
	FileQueryResponse_UNKNOWN       FileQueryResponse_Status = 0
	FileQueryResponse_INVALID_PARAM FileQueryResponse_Status = -1
	FileQueryResponse_SUCCESS       FileQueryResponse_Status = 1
	FileQueryResponse_NOT_FOUND     FileQueryResponse_Status = 2
)

var FileQueryResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "NOT_FOUND",
}

var FileQueryResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"NOT_FOUND":     2,
}

func (x FileQueryResponse_Status) String() string {
	return proto.EnumName(FileQueryResponse_Status_name, int32(x))
}

func (FileQueryResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2, 0}
}

type FileCreateResponse_Status int32

const (
	FileCreateResponse_UNKNOWN       FileCreateResponse_Status = 0
	FileCreateResponse_INVALID_PARAM FileCreateResponse_Status = -1
	FileCreateResponse_SUCCESS       FileCreateResponse_Status = 1
)

var FileCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
}

var FileCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
}

func (x FileCreateResponse_Status) String() string {
	return proto.EnumName(FileCreateResponse_Status_name, int32(x))
}

func (FileCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{4, 0}
}

type FileRequest struct {
	FileId               string   `protobuf:"bytes,1,opt,name=fileId,proto3" json:"fileId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileRequest) Reset()         { *m = FileRequest{} }
func (m *FileRequest) String() string { return proto.CompactTextString(m) }
func (*FileRequest) ProtoMessage()    {}
func (*FileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{0}
}

func (m *FileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileRequest.Unmarshal(m, b)
}
func (m *FileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileRequest.Marshal(b, m, deterministic)
}
func (m *FileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileRequest.Merge(m, src)
}
func (m *FileRequest) XXX_Size() int {
	return xxx_messageInfo_FileRequest.Size(m)
}
func (m *FileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileRequest proto.InternalMessageInfo

func (m *FileRequest) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

type FileDeleteResponse struct {
	Status               FileDeleteResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=FileDeleteResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FileDeleteResponse) Reset()         { *m = FileDeleteResponse{} }
func (m *FileDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*FileDeleteResponse) ProtoMessage()    {}
func (*FileDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{1}
}

func (m *FileDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileDeleteResponse.Unmarshal(m, b)
}
func (m *FileDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileDeleteResponse.Marshal(b, m, deterministic)
}
func (m *FileDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileDeleteResponse.Merge(m, src)
}
func (m *FileDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_FileDeleteResponse.Size(m)
}
func (m *FileDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileDeleteResponse proto.InternalMessageInfo

func (m *FileDeleteResponse) GetStatus() FileDeleteResponse_Status {
	if m != nil {
		return m.Status
	}
	return FileDeleteResponse_UNKNOWN
}

type FileQueryResponse struct {
	Status               FileQueryResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=FileQueryResponse_Status" json:"status,omitempty"`
	File                 []byte                   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	Size                 int64                    `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *FileQueryResponse) Reset()         { *m = FileQueryResponse{} }
func (m *FileQueryResponse) String() string { return proto.CompactTextString(m) }
func (*FileQueryResponse) ProtoMessage()    {}
func (*FileQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{2}
}

func (m *FileQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileQueryResponse.Unmarshal(m, b)
}
func (m *FileQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileQueryResponse.Marshal(b, m, deterministic)
}
func (m *FileQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileQueryResponse.Merge(m, src)
}
func (m *FileQueryResponse) XXX_Size() int {
	return xxx_messageInfo_FileQueryResponse.Size(m)
}
func (m *FileQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileQueryResponse proto.InternalMessageInfo

func (m *FileQueryResponse) GetStatus() FileQueryResponse_Status {
	if m != nil {
		return m.Status
	}
	return FileQueryResponse_UNKNOWN
}

func (m *FileQueryResponse) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

func (m *FileQueryResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type FileCreateRequest struct {
	File                 []byte   `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileCreateRequest) Reset()         { *m = FileCreateRequest{} }
func (m *FileCreateRequest) String() string { return proto.CompactTextString(m) }
func (*FileCreateRequest) ProtoMessage()    {}
func (*FileCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{3}
}

func (m *FileCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCreateRequest.Unmarshal(m, b)
}
func (m *FileCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCreateRequest.Marshal(b, m, deterministic)
}
func (m *FileCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCreateRequest.Merge(m, src)
}
func (m *FileCreateRequest) XXX_Size() int {
	return xxx_messageInfo_FileCreateRequest.Size(m)
}
func (m *FileCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FileCreateRequest proto.InternalMessageInfo

func (m *FileCreateRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type FileCreateResponse struct {
	Status               FileCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=FileCreateResponse_Status" json:"status,omitempty"`
	FileId               string                    `protobuf:"bytes,2,opt,name=fileId,proto3" json:"fileId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FileCreateResponse) Reset()         { *m = FileCreateResponse{} }
func (m *FileCreateResponse) String() string { return proto.CompactTextString(m) }
func (*FileCreateResponse) ProtoMessage()    {}
func (*FileCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9188e3b7e55e1162, []int{4}
}

func (m *FileCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileCreateResponse.Unmarshal(m, b)
}
func (m *FileCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileCreateResponse.Marshal(b, m, deterministic)
}
func (m *FileCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileCreateResponse.Merge(m, src)
}
func (m *FileCreateResponse) XXX_Size() int {
	return xxx_messageInfo_FileCreateResponse.Size(m)
}
func (m *FileCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FileCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FileCreateResponse proto.InternalMessageInfo

func (m *FileCreateResponse) GetStatus() FileCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return FileCreateResponse_UNKNOWN
}

func (m *FileCreateResponse) GetFileId() string {
	if m != nil {
		return m.FileId
	}
	return ""
}

func init() {
	proto.RegisterEnum("FileDeleteResponse_Status", FileDeleteResponse_Status_name, FileDeleteResponse_Status_value)
	proto.RegisterEnum("FileQueryResponse_Status", FileQueryResponse_Status_name, FileQueryResponse_Status_value)
	proto.RegisterEnum("FileCreateResponse_Status", FileCreateResponse_Status_name, FileCreateResponse_Status_value)
	proto.RegisterType((*FileRequest)(nil), "FileRequest")
	proto.RegisterType((*FileDeleteResponse)(nil), "FileDeleteResponse")
	proto.RegisterType((*FileQueryResponse)(nil), "FileQueryResponse")
	proto.RegisterType((*FileCreateRequest)(nil), "FileCreateRequest")
	proto.RegisterType((*FileCreateResponse)(nil), "FileCreateResponse")
}

func init() { proto.RegisterFile("file.proto", fileDescriptor_9188e3b7e55e1162) }

var fileDescriptor_9188e3b7e55e1162 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xcb, 0xcc, 0x49,
	0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x52, 0xe5, 0xe2, 0x76, 0xcb, 0xcc, 0x49, 0x0d, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0x12, 0xe3, 0x62, 0x03, 0x49, 0x7a, 0xa6, 0x48, 0x30, 0x2a,
	0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x4a, 0xd3, 0x19, 0xb9, 0x84, 0x40, 0xea, 0x5c, 0x52, 0x73,
	0x52, 0x4b, 0x52, 0x83, 0x52, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x8c, 0xb8, 0xd8, 0x8a,
	0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0xc1, 0xca, 0xf9, 0x8c, 0xa4, 0xf4, 0x30, 0x15, 0xe9, 0x05, 0x83,
	0x55, 0x04, 0x41, 0x55, 0x2a, 0xf9, 0x72, 0xb1, 0x41, 0x44, 0x84, 0xb8, 0xb9, 0xd8, 0x43, 0xfd,
	0xbc, 0xfd, 0xfc, 0xc3, 0xfd, 0x04, 0x18, 0x84, 0xa4, 0xb8, 0x78, 0x3d, 0xfd, 0xc2, 0x1c, 0x7d,
	0x3c, 0x5d, 0xe2, 0x03, 0x1c, 0x83, 0x1c, 0x7d, 0x05, 0xfe, 0xc3, 0x00, 0x23, 0x48, 0x61, 0x70,
	0xa8, 0xb3, 0xb3, 0x6b, 0x70, 0xb0, 0x00, 0xa3, 0x10, 0x2f, 0x17, 0xa7, 0x9f, 0x7f, 0x48, 0xbc,
	0x9b, 0x7f, 0xa8, 0x9f, 0x8b, 0x00, 0x93, 0xd2, 0x5e, 0x46, 0x2e, 0x41, 0x90, 0xa5, 0x81, 0xa5,
	0xa9, 0x45, 0x95, 0x70, 0x87, 0x19, 0xa2, 0x39, 0x4c, 0x52, 0x0f, 0x43, 0x0d, 0x9a, 0xbb, 0x84,
	0x84, 0xb8, 0x58, 0x40, 0x9e, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x02, 0xb3, 0x41, 0x62,
	0xc5, 0x99, 0x55, 0xa9, 0x12, 0xcc, 0x0a, 0x8c, 0x1a, 0xcc, 0x41, 0x60, 0x36, 0xb5, 0xdd, 0xaf,
	0x0e, 0x71, 0xbe, 0x73, 0x51, 0x6a, 0x62, 0x09, 0x3c, 0x1a, 0x60, 0x6e, 0x61, 0x44, 0xb8, 0x45,
	0x69, 0x01, 0x34, 0x0a, 0x60, 0x2a, 0xf1, 0x46, 0x01, 0xaa, 0x22, 0x74, 0xaf, 0x22, 0x62, 0x99,
	0x09, 0x25, 0x96, 0xed, 0x28, 0xf3, 0x9a, 0xd1, 0x44, 0x46, 0x2e, 0x16, 0x90, 0xed, 0x42, 0x9a,
	0x5c, 0xac, 0xe0, 0xb0, 0x16, 0xe2, 0xd1, 0x43, 0x4a, 0x5d, 0x52, 0x42, 0x7a, 0x58, 0x63, 0x0a,
	0xe2, 0x58, 0x21, 0x21, 0x3d, 0x8c, 0x80, 0x90, 0x12, 0xc6, 0xe2, 0x1b, 0x21, 0x6d, 0x2e, 0x36,
	0x48, 0x12, 0x43, 0x33, 0x5e, 0x18, 0x4b, 0xea, 0x4b, 0x62, 0x03, 0xa7, 0x73, 0x63, 0x40, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x88, 0xff, 0x69, 0xc5, 0xf5, 0x02, 0x00, 0x00,
}
