// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sellinfo.proto

package sellinfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SellStatus int32

const (
	SellStatus_UNKNOWN  SellStatus = 0
	SellStatus_SELLING  SellStatus = 1
	SellStatus_RESERVED SellStatus = 2
	SellStatus_DONE     SellStatus = 3
	SellStatus_EXPIRED  SellStatus = 4
	SellStatus_CLOSED   SellStatus = 5
)

var SellStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SELLING",
	2: "RESERVED",
	3: "DONE",
	4: "EXPIRED",
	5: "CLOSED",
}

var SellStatus_value = map[string]int32{
	"UNKNOWN":  0,
	"SELLING":  1,
	"RESERVED": 2,
	"DONE":     3,
	"EXPIRED":  4,
	"CLOSED":   5,
}

func (x SellStatus) String() string {
	return proto.EnumName(SellStatus_name, int32(x))
}

func (SellStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{0}
}

type SellInfoCreateResponse_Status int32

const (
	SellInfoCreateResponse_UNKNOWN       SellInfoCreateResponse_Status = 0
	SellInfoCreateResponse_INVALID_PARAM SellInfoCreateResponse_Status = -1
	SellInfoCreateResponse_SUCCESS       SellInfoCreateResponse_Status = 1
	SellInfoCreateResponse_INVALID_TOKEN SellInfoCreateResponse_Status = 2
)

var SellInfoCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "INVALID_TOKEN",
}

var SellInfoCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"INVALID_TOKEN": 2,
}

func (x SellInfoCreateResponse_Status) String() string {
	return proto.EnumName(SellInfoCreateResponse_Status_name, int32(x))
}

func (SellInfoCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{3, 0}
}

type SellInfoUpdateResponse_Status int32

const (
	SellInfoUpdateResponse_UNKNOWN       SellInfoUpdateResponse_Status = 0
	SellInfoUpdateResponse_INVALID_PARAM SellInfoUpdateResponse_Status = -1
	SellInfoUpdateResponse_SUCCESS       SellInfoUpdateResponse_Status = 1
	SellInfoUpdateResponse_NOT_FOUND     SellInfoUpdateResponse_Status = 2
)

var SellInfoUpdateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "NOT_FOUND",
}

var SellInfoUpdateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"NOT_FOUND":     2,
}

func (x SellInfoUpdateResponse_Status) String() string {
	return proto.EnumName(SellInfoUpdateResponse_Status_name, int32(x))
}

func (SellInfoUpdateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{7, 0}
}

type SellInfoMsg struct {
	SellInfoID           int32      `protobuf:"varint,1,opt,name=sellInfoID,proto3" json:"sellInfoID,omitempty"`
	Status               SellStatus `protobuf:"varint,2,opt,name=status,proto3,enum=SellStatus" json:"status,omitempty"`
	ReleaseTime          int64      `protobuf:"varint,3,opt,name=releaseTime,proto3" json:"releaseTime,omitempty"`
	ValidTime            int64      `protobuf:"varint,4,opt,name=validTime,proto3" json:"validTime,omitempty"`
	GoodName             string     `protobuf:"bytes,5,opt,name=goodName,proto3" json:"goodName,omitempty"`
	Price                float64    `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Description          string     `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ContentID            string     `protobuf:"bytes,8,opt,name=contentID,proto3" json:"contentID,omitempty"`
	UserID               int32      `protobuf:"varint,9,opt,name=userID,proto3" json:"userID,omitempty"`
	ClearEmpty           bool       `protobuf:"varint,99,opt,name=clearEmpty,proto3" json:"clearEmpty,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SellInfoMsg) Reset()         { *m = SellInfoMsg{} }
func (m *SellInfoMsg) String() string { return proto.CompactTextString(m) }
func (*SellInfoMsg) ProtoMessage()    {}
func (*SellInfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{0}
}

func (m *SellInfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfoMsg.Unmarshal(m, b)
}
func (m *SellInfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfoMsg.Marshal(b, m, deterministic)
}
func (m *SellInfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfoMsg.Merge(m, src)
}
func (m *SellInfoMsg) XXX_Size() int {
	return xxx_messageInfo_SellInfoMsg.Size(m)
}
func (m *SellInfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfoMsg proto.InternalMessageInfo

func (m *SellInfoMsg) GetSellInfoID() int32 {
	if m != nil {
		return m.SellInfoID
	}
	return 0
}

func (m *SellInfoMsg) GetStatus() SellStatus {
	if m != nil {
		return m.Status
	}
	return SellStatus_UNKNOWN
}

func (m *SellInfoMsg) GetReleaseTime() int64 {
	if m != nil {
		return m.ReleaseTime
	}
	return 0
}

func (m *SellInfoMsg) GetValidTime() int64 {
	if m != nil {
		return m.ValidTime
	}
	return 0
}

func (m *SellInfoMsg) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *SellInfoMsg) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SellInfoMsg) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SellInfoMsg) GetContentID() string {
	if m != nil {
		return m.ContentID
	}
	return ""
}

func (m *SellInfoMsg) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SellInfoMsg) GetClearEmpty() bool {
	if m != nil {
		return m.ClearEmpty
	}
	return false
}

type SellInfoQueryRequest struct {
	SellInfoID           int32    `protobuf:"varint,1,opt,name=sellInfoID,proto3" json:"sellInfoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellInfoQueryRequest) Reset()         { *m = SellInfoQueryRequest{} }
func (m *SellInfoQueryRequest) String() string { return proto.CompactTextString(m) }
func (*SellInfoQueryRequest) ProtoMessage()    {}
func (*SellInfoQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{1}
}

func (m *SellInfoQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfoQueryRequest.Unmarshal(m, b)
}
func (m *SellInfoQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfoQueryRequest.Marshal(b, m, deterministic)
}
func (m *SellInfoQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfoQueryRequest.Merge(m, src)
}
func (m *SellInfoQueryRequest) XXX_Size() int {
	return xxx_messageInfo_SellInfoQueryRequest.Size(m)
}
func (m *SellInfoQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfoQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfoQueryRequest proto.InternalMessageInfo

func (m *SellInfoQueryRequest) GetSellInfoID() int32 {
	if m != nil {
		return m.SellInfoID
	}
	return 0
}

type SellInfoCreateRequest struct {
	ValidTime            int64    `protobuf:"varint,1,opt,name=validTime,proto3" json:"validTime,omitempty"`
	GoodName             string   `protobuf:"bytes,2,opt,name=goodName,proto3" json:"goodName,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ContentID            string   `protobuf:"bytes,5,opt,name=contentID,proto3" json:"contentID,omitempty"`
	ContentToken         string   `protobuf:"bytes,6,opt,name=contentToken,proto3" json:"contentToken,omitempty"`
	UserID               int32    `protobuf:"varint,7,opt,name=userID,proto3" json:"userID,omitempty"`
	Tags                 []string `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SellInfoCreateRequest) Reset()         { *m = SellInfoCreateRequest{} }
func (m *SellInfoCreateRequest) String() string { return proto.CompactTextString(m) }
func (*SellInfoCreateRequest) ProtoMessage()    {}
func (*SellInfoCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{2}
}

func (m *SellInfoCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfoCreateRequest.Unmarshal(m, b)
}
func (m *SellInfoCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfoCreateRequest.Marshal(b, m, deterministic)
}
func (m *SellInfoCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfoCreateRequest.Merge(m, src)
}
func (m *SellInfoCreateRequest) XXX_Size() int {
	return xxx_messageInfo_SellInfoCreateRequest.Size(m)
}
func (m *SellInfoCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfoCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfoCreateRequest proto.InternalMessageInfo

func (m *SellInfoCreateRequest) GetValidTime() int64 {
	if m != nil {
		return m.ValidTime
	}
	return 0
}

func (m *SellInfoCreateRequest) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *SellInfoCreateRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *SellInfoCreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SellInfoCreateRequest) GetContentID() string {
	if m != nil {
		return m.ContentID
	}
	return ""
}

func (m *SellInfoCreateRequest) GetContentToken() string {
	if m != nil {
		return m.ContentToken
	}
	return ""
}

func (m *SellInfoCreateRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SellInfoCreateRequest) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type SellInfoCreateResponse struct {
	Status               SellInfoCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=SellInfoCreateResponse_Status" json:"status,omitempty"`
	SellInfoID           int32                         `protobuf:"varint,2,opt,name=sellInfoID,proto3" json:"sellInfoID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SellInfoCreateResponse) Reset()         { *m = SellInfoCreateResponse{} }
func (m *SellInfoCreateResponse) String() string { return proto.CompactTextString(m) }
func (*SellInfoCreateResponse) ProtoMessage()    {}
func (*SellInfoCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{3}
}

func (m *SellInfoCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfoCreateResponse.Unmarshal(m, b)
}
func (m *SellInfoCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfoCreateResponse.Marshal(b, m, deterministic)
}
func (m *SellInfoCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfoCreateResponse.Merge(m, src)
}
func (m *SellInfoCreateResponse) XXX_Size() int {
	return xxx_messageInfo_SellInfoCreateResponse.Size(m)
}
func (m *SellInfoCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfoCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfoCreateResponse proto.InternalMessageInfo

func (m *SellInfoCreateResponse) GetStatus() SellInfoCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return SellInfoCreateResponse_UNKNOWN
}

func (m *SellInfoCreateResponse) GetSellInfoID() int32 {
	if m != nil {
		return m.SellInfoID
	}
	return 0
}

type SellInfoFindRequest struct {
	UserID               int32      `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Status               SellStatus `protobuf:"varint,2,opt,name=status,proto3,enum=SellStatus" json:"status,omitempty"`
	GoodName             string     `protobuf:"bytes,3,opt,name=goodName,proto3" json:"goodName,omitempty"`
	LowPrice             float64    `protobuf:"fixed64,4,opt,name=lowPrice,proto3" json:"lowPrice,omitempty"`
	HighPrice            float64    `protobuf:"fixed64,5,opt,name=highPrice,proto3" json:"highPrice,omitempty"`
	Limit                uint32     `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32     `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SellInfoFindRequest) Reset()         { *m = SellInfoFindRequest{} }
func (m *SellInfoFindRequest) String() string { return proto.CompactTextString(m) }
func (*SellInfoFindRequest) ProtoMessage()    {}
func (*SellInfoFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{4}
}

func (m *SellInfoFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfoFindRequest.Unmarshal(m, b)
}
func (m *SellInfoFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfoFindRequest.Marshal(b, m, deterministic)
}
func (m *SellInfoFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfoFindRequest.Merge(m, src)
}
func (m *SellInfoFindRequest) XXX_Size() int {
	return xxx_messageInfo_SellInfoFindRequest.Size(m)
}
func (m *SellInfoFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfoFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfoFindRequest proto.InternalMessageInfo

func (m *SellInfoFindRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *SellInfoFindRequest) GetStatus() SellStatus {
	if m != nil {
		return m.Status
	}
	return SellStatus_UNKNOWN
}

func (m *SellInfoFindRequest) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *SellInfoFindRequest) GetLowPrice() float64 {
	if m != nil {
		return m.LowPrice
	}
	return 0
}

func (m *SellInfoFindRequest) GetHighPrice() float64 {
	if m != nil {
		return m.HighPrice
	}
	return 0
}

func (m *SellInfoFindRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SellInfoFindRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type SellInfoFindResponse struct {
	SellInfo             []*SellInfoMsg `protobuf:"bytes,1,rep,name=sellInfo,proto3" json:"sellInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SellInfoFindResponse) Reset()         { *m = SellInfoFindResponse{} }
func (m *SellInfoFindResponse) String() string { return proto.CompactTextString(m) }
func (*SellInfoFindResponse) ProtoMessage()    {}
func (*SellInfoFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{5}
}

func (m *SellInfoFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfoFindResponse.Unmarshal(m, b)
}
func (m *SellInfoFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfoFindResponse.Marshal(b, m, deterministic)
}
func (m *SellInfoFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfoFindResponse.Merge(m, src)
}
func (m *SellInfoFindResponse) XXX_Size() int {
	return xxx_messageInfo_SellInfoFindResponse.Size(m)
}
func (m *SellInfoFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfoFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfoFindResponse proto.InternalMessageInfo

func (m *SellInfoFindResponse) GetSellInfo() []*SellInfoMsg {
	if m != nil {
		return m.SellInfo
	}
	return nil
}

type SellInfoUpdateRequest struct {
	SellInfoID           int32      `protobuf:"varint,1,opt,name=sellInfoID,proto3" json:"sellInfoID,omitempty"`
	Status               SellStatus `protobuf:"varint,2,opt,name=status,proto3,enum=SellStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SellInfoUpdateRequest) Reset()         { *m = SellInfoUpdateRequest{} }
func (m *SellInfoUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*SellInfoUpdateRequest) ProtoMessage()    {}
func (*SellInfoUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{6}
}

func (m *SellInfoUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfoUpdateRequest.Unmarshal(m, b)
}
func (m *SellInfoUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfoUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SellInfoUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfoUpdateRequest.Merge(m, src)
}
func (m *SellInfoUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SellInfoUpdateRequest.Size(m)
}
func (m *SellInfoUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfoUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfoUpdateRequest proto.InternalMessageInfo

func (m *SellInfoUpdateRequest) GetSellInfoID() int32 {
	if m != nil {
		return m.SellInfoID
	}
	return 0
}

func (m *SellInfoUpdateRequest) GetStatus() SellStatus {
	if m != nil {
		return m.Status
	}
	return SellStatus_UNKNOWN
}

type SellInfoUpdateResponse struct {
	Status               SellInfoUpdateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=SellInfoUpdateResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *SellInfoUpdateResponse) Reset()         { *m = SellInfoUpdateResponse{} }
func (m *SellInfoUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*SellInfoUpdateResponse) ProtoMessage()    {}
func (*SellInfoUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9c322b32f573704b, []int{7}
}

func (m *SellInfoUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SellInfoUpdateResponse.Unmarshal(m, b)
}
func (m *SellInfoUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SellInfoUpdateResponse.Marshal(b, m, deterministic)
}
func (m *SellInfoUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SellInfoUpdateResponse.Merge(m, src)
}
func (m *SellInfoUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_SellInfoUpdateResponse.Size(m)
}
func (m *SellInfoUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SellInfoUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SellInfoUpdateResponse proto.InternalMessageInfo

func (m *SellInfoUpdateResponse) GetStatus() SellInfoUpdateResponse_Status {
	if m != nil {
		return m.Status
	}
	return SellInfoUpdateResponse_UNKNOWN
}

func init() {
	proto.RegisterEnum("SellStatus", SellStatus_name, SellStatus_value)
	proto.RegisterEnum("SellInfoCreateResponse_Status", SellInfoCreateResponse_Status_name, SellInfoCreateResponse_Status_value)
	proto.RegisterEnum("SellInfoUpdateResponse_Status", SellInfoUpdateResponse_Status_name, SellInfoUpdateResponse_Status_value)
	proto.RegisterType((*SellInfoMsg)(nil), "SellInfoMsg")
	proto.RegisterType((*SellInfoQueryRequest)(nil), "SellInfoQueryRequest")
	proto.RegisterType((*SellInfoCreateRequest)(nil), "SellInfoCreateRequest")
	proto.RegisterType((*SellInfoCreateResponse)(nil), "SellInfoCreateResponse")
	proto.RegisterType((*SellInfoFindRequest)(nil), "SellInfoFindRequest")
	proto.RegisterType((*SellInfoFindResponse)(nil), "SellInfoFindResponse")
	proto.RegisterType((*SellInfoUpdateRequest)(nil), "SellInfoUpdateRequest")
	proto.RegisterType((*SellInfoUpdateResponse)(nil), "SellInfoUpdateResponse")
}

func init() { proto.RegisterFile("sellinfo.proto", fileDescriptor_9c322b32f573704b) }

var fileDescriptor_9c322b32f573704b = []byte{
	// 694 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xcd, 0x6e, 0x9b, 0x4a,
	0x14, 0xbe, 0x63, 0x7e, 0x82, 0x8f, 0xe3, 0x88, 0x3b, 0x37, 0xc9, 0x45, 0xd6, 0x55, 0x84, 0xb8,
	0x1b, 0x54, 0x55, 0x2c, 0x12, 0x29, 0x52, 0x76, 0x8d, 0x0c, 0xa9, 0x50, 0x1c, 0x9c, 0x0c, 0x76,
	0xd2, 0x45, 0xa5, 0x88, 0xda, 0x63, 0x07, 0x15, 0x83, 0x0b, 0xb8, 0x55, 0x9e, 0xa6, 0x2f, 0xd2,
	0x5d, 0xdf, 0xa1, 0x2f, 0xd0, 0x87, 0xe8, 0xb2, 0x15, 0x83, 0x31, 0xe0, 0x3a, 0x49, 0xa5, 0xd6,
	0x2b, 0x9f, 0xef, 0x9c, 0x33, 0x3f, 0xdf, 0xf7, 0xcd, 0x01, 0x76, 0x12, 0x1a, 0x04, 0x7e, 0x38,
	0x89, 0x8c, 0x79, 0x1c, 0xa5, 0x91, 0xf6, 0xa9, 0x01, 0x2d, 0x97, 0x06, 0x81, 0x1d, 0x4e, 0xa2,
	0x8b, 0x64, 0x8a, 0x0f, 0x00, 0x92, 0x65, 0x68, 0x9b, 0x0a, 0x52, 0x91, 0x2e, 0x90, 0x0a, 0x82,
	0xff, 0x07, 0x31, 0x49, 0xbd, 0x74, 0x91, 0x28, 0x0d, 0x15, 0xe9, 0x3b, 0x87, 0x2d, 0x23, 0xeb,
	0x76, 0x19, 0x44, 0x96, 0x29, 0xac, 0x42, 0x2b, 0xa6, 0x01, 0xf5, 0x12, 0x3a, 0xf0, 0x67, 0x54,
	0xe1, 0x54, 0xa4, 0x73, 0xa4, 0x0a, 0xe1, 0xff, 0xa0, 0xf9, 0xde, 0x0b, 0xfc, 0x31, 0xcb, 0xf3,
	0x2c, 0x5f, 0x02, 0xb8, 0x03, 0xd2, 0x34, 0x8a, 0xc6, 0x8e, 0x37, 0xa3, 0x8a, 0xa0, 0x22, 0xbd,
	0x49, 0x56, 0x31, 0xde, 0x05, 0x61, 0x1e, 0xfb, 0x23, 0xaa, 0x88, 0x2a, 0xd2, 0x11, 0xc9, 0x83,
	0x6c, 0xc7, 0x31, 0x4d, 0x46, 0xb1, 0x3f, 0x4f, 0xfd, 0x28, 0x54, 0xb6, 0x58, 0x53, 0x15, 0xca,
	0x76, 0x1c, 0x45, 0x61, 0x4a, 0xc3, 0xd4, 0x36, 0x15, 0x89, 0xe5, 0x4b, 0x00, 0xef, 0x83, 0xb8,
	0x48, 0x68, 0x6c, 0x9b, 0x4a, 0x93, 0x5d, 0x79, 0x19, 0x65, 0x74, 0x8c, 0x02, 0xea, 0xc5, 0xd6,
	0x6c, 0x9e, 0xde, 0x2b, 0x23, 0x15, 0xe9, 0x12, 0xa9, 0x20, 0xda, 0x31, 0xec, 0x16, 0xec, 0x5d,
	0x2d, 0x68, 0x7c, 0x4f, 0xe8, 0xbb, 0x05, 0x4d, 0xd2, 0xa7, 0x68, 0xd4, 0xbe, 0x21, 0xd8, 0x2b,
	0x1a, 0xbb, 0x31, 0xf5, 0x52, 0x5a, 0x74, 0xd6, 0x98, 0x41, 0x8f, 0x31, 0xd3, 0x78, 0x88, 0x19,
	0xee, 0x11, 0x66, 0xf8, 0x27, 0x98, 0x11, 0xd6, 0x99, 0xd1, 0x60, 0x7b, 0x19, 0x0c, 0xa2, 0xb7,
	0x34, 0x64, 0xb4, 0x37, 0x49, 0x0d, 0xab, 0xb0, 0xb7, 0x55, 0x63, 0x0f, 0x03, 0x9f, 0x7a, 0xd3,
	0x44, 0x91, 0x54, 0x4e, 0x6f, 0x12, 0xf6, 0x5f, 0xfb, 0x8c, 0x60, 0x7f, 0xfd, 0xe6, 0xc9, 0x3c,
	0x0a, 0x13, 0x8a, 0x8f, 0x57, 0xde, 0x42, 0xcc, 0x5b, 0x07, 0xc6, 0xe6, 0x42, 0x63, 0xcd, 0x6e,
	0x75, 0xb2, 0x1b, 0x3f, 0x91, 0x7d, 0x05, 0x62, 0xde, 0x81, 0x5b, 0xb0, 0x35, 0x74, 0xce, 0x9d,
	0xfe, 0x8d, 0x23, 0xff, 0x85, 0x3b, 0xd0, 0xb6, 0x9d, 0xeb, 0xd3, 0x9e, 0x6d, 0xde, 0x5e, 0x9e,
	0x92, 0xd3, 0x0b, 0xf9, 0x7b, 0xf1, 0x43, 0x59, 0xa1, 0x3b, 0xec, 0x76, 0x2d, 0xd7, 0x95, 0x11,
	0xfe, 0xbb, 0x2c, 0x1c, 0xf4, 0xcf, 0x2d, 0x47, 0x6e, 0x68, 0x5f, 0x10, 0xfc, 0x53, 0x1c, 0xee,
	0xcc, 0x0f, 0xc7, 0x85, 0x7a, 0x25, 0x13, 0xa8, 0xc6, 0xc4, 0x2f, 0x3d, 0x9b, 0xaa, 0xb8, 0xdc,
	0x9a, 0xb8, 0x1d, 0x90, 0x82, 0xe8, 0xc3, 0x25, 0xd3, 0x97, 0x67, 0xfa, 0xae, 0xe2, 0x4c, 0xc0,
	0x3b, 0x7f, 0x7a, 0x97, 0x27, 0x05, 0x96, 0x2c, 0x81, 0xcc, 0x16, 0x81, 0x3f, 0xf3, 0x53, 0xa6,
	0x5c, 0x9b, 0xe4, 0x41, 0x76, 0xd0, 0x68, 0x32, 0x49, 0x68, 0xca, 0x24, 0x6b, 0x93, 0x65, 0xa4,
	0xbd, 0x28, 0x0d, 0x9d, 0xdf, 0x6b, 0xa9, 0x8d, 0x0e, 0x52, 0xc1, 0xa8, 0x82, 0x54, 0x4e, 0x6f,
	0x1d, 0x6e, 0x1b, 0x95, 0xb9, 0x41, 0x56, 0x59, 0xed, 0x75, 0xe9, 0xec, 0xe1, 0x7c, 0x5c, 0x71,
	0xf6, 0x9f, 0x18, 0x2d, 0xda, 0xc7, 0x8a, 0x7d, 0x8a, 0xe5, 0x9f, 0xb4, 0x4f, 0xbd, 0x70, 0xcd,
	0x3e, 0xda, 0xc5, 0x6f, 0xda, 0xa3, 0x0d, 0x4d, 0xa7, 0x3f, 0xb8, 0x3d, 0xeb, 0x0f, 0x1d, 0x53,
	0x6e, 0x3c, 0xbb, 0x01, 0x28, 0xcf, 0x5d, 0x5f, 0x32, 0x6b, 0xb3, 0x7a, 0x3d, 0xdb, 0x79, 0x29,
	0x23, 0xbc, 0x0d, 0x12, 0xb1, 0x5c, 0x8b, 0x5c, 0x5b, 0xa6, 0xdc, 0xc0, 0x12, 0xf0, 0x66, 0xdf,
	0xb1, 0x64, 0x2e, 0x2b, 0xb2, 0x5e, 0x5d, 0xda, 0xc4, 0x32, 0x65, 0x1e, 0x03, 0x88, 0xdd, 0x5e,
	0xdf, 0xb5, 0x4c, 0x59, 0x38, 0xfc, 0x8a, 0x40, 0x2a, 0x6e, 0x84, 0x9f, 0x83, 0xc0, 0x06, 0x0e,
	0xde, 0x33, 0x36, 0x0d, 0xa0, 0x4e, 0x4d, 0x1d, 0x7c, 0x02, 0x62, 0xfe, 0x84, 0xf0, 0xbe, 0xb1,
	0x71, 0xec, 0x74, 0xfe, 0x7d, 0xe0, 0xad, 0xe1, 0x23, 0xe0, 0x33, 0x23, 0xe0, 0x5d, 0x63, 0x83,
	0xdf, 0x3b, 0x7b, 0xc6, 0x46, 0xb7, 0x9c, 0x80, 0x98, 0x73, 0x5e, 0xd9, 0xaf, 0x66, 0x86, 0xca,
	0x7e, 0x75, 0x71, 0xde, 0x88, 0xec, 0xbb, 0x74, 0xf4, 0x23, 0x00, 0x00, 0xff, 0xff, 0x82, 0xcc,
	0x52, 0x31, 0xa9, 0x06, 0x00, 0x00,
}
