// Code generated by protoc-gen-go. DO NOT EDIT.
// source: buyinfo.proto

package buyinfo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type BuyInfoCreateResponse_Status int32

const (
	BuyInfoCreateResponse_UNKNOWN       BuyInfoCreateResponse_Status = 0
	BuyInfoCreateResponse_INVALID_PARAM BuyInfoCreateResponse_Status = -1
	BuyInfoCreateResponse_SUCCESS       BuyInfoCreateResponse_Status = 1
	BuyInfoCreateResponse_INVALID_TOKEN BuyInfoCreateResponse_Status = 2
)

var BuyInfoCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "INVALID_TOKEN",
}

var BuyInfoCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"INVALID_TOKEN": 2,
}

func (x BuyInfoCreateResponse_Status) String() string {
	return proto.EnumName(BuyInfoCreateResponse_Status_name, int32(x))
}

func (BuyInfoCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0e8250a94d2d8d95, []int{3, 0}
}

type BuyInfoMsg struct {
	BuyInfoId            int32    `protobuf:"varint,1,opt,name=buyInfoId,proto3" json:"buyInfoId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	ReleaseTime          int64    `protobuf:"varint,3,opt,name=releaseTime,proto3" json:"releaseTime,omitempty"`
	ValidTime            int64    `protobuf:"varint,4,opt,name=validTime,proto3" json:"validTime,omitempty"`
	GoodName             string   `protobuf:"bytes,5,opt,name=goodName,proto3" json:"goodName,omitempty"`
	Price                float64  `protobuf:"fixed64,6,opt,name=price,proto3" json:"price,omitempty"`
	Description          string   `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	ContentId            string   `protobuf:"bytes,8,opt,name=contentId,proto3" json:"contentId,omitempty"`
	UserId               int32    `protobuf:"varint,9,opt,name=userId,proto3" json:"userId,omitempty"`
	ClearEmpty           bool     `protobuf:"varint,99,opt,name=clearEmpty,proto3" json:"clearEmpty,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyInfoMsg) Reset()         { *m = BuyInfoMsg{} }
func (m *BuyInfoMsg) String() string { return proto.CompactTextString(m) }
func (*BuyInfoMsg) ProtoMessage()    {}
func (*BuyInfoMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e8250a94d2d8d95, []int{0}
}

func (m *BuyInfoMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyInfoMsg.Unmarshal(m, b)
}
func (m *BuyInfoMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyInfoMsg.Marshal(b, m, deterministic)
}
func (m *BuyInfoMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyInfoMsg.Merge(m, src)
}
func (m *BuyInfoMsg) XXX_Size() int {
	return xxx_messageInfo_BuyInfoMsg.Size(m)
}
func (m *BuyInfoMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyInfoMsg.DiscardUnknown(m)
}

var xxx_messageInfo_BuyInfoMsg proto.InternalMessageInfo

func (m *BuyInfoMsg) GetBuyInfoId() int32 {
	if m != nil {
		return m.BuyInfoId
	}
	return 0
}

func (m *BuyInfoMsg) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BuyInfoMsg) GetReleaseTime() int64 {
	if m != nil {
		return m.ReleaseTime
	}
	return 0
}

func (m *BuyInfoMsg) GetValidTime() int64 {
	if m != nil {
		return m.ValidTime
	}
	return 0
}

func (m *BuyInfoMsg) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *BuyInfoMsg) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BuyInfoMsg) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BuyInfoMsg) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *BuyInfoMsg) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BuyInfoMsg) GetClearEmpty() bool {
	if m != nil {
		return m.ClearEmpty
	}
	return false
}

type BuyInfoQueryRequest struct {
	BuyInfoId            int32    `protobuf:"varint,1,opt,name=buyInfoId,proto3" json:"buyInfoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyInfoQueryRequest) Reset()         { *m = BuyInfoQueryRequest{} }
func (m *BuyInfoQueryRequest) String() string { return proto.CompactTextString(m) }
func (*BuyInfoQueryRequest) ProtoMessage()    {}
func (*BuyInfoQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e8250a94d2d8d95, []int{1}
}

func (m *BuyInfoQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyInfoQueryRequest.Unmarshal(m, b)
}
func (m *BuyInfoQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyInfoQueryRequest.Marshal(b, m, deterministic)
}
func (m *BuyInfoQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyInfoQueryRequest.Merge(m, src)
}
func (m *BuyInfoQueryRequest) XXX_Size() int {
	return xxx_messageInfo_BuyInfoQueryRequest.Size(m)
}
func (m *BuyInfoQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyInfoQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuyInfoQueryRequest proto.InternalMessageInfo

func (m *BuyInfoQueryRequest) GetBuyInfoId() int32 {
	if m != nil {
		return m.BuyInfoId
	}
	return 0
}

type BuyInfoCreateRequest struct {
	ValidTime            int64    `protobuf:"varint,1,opt,name=validTime,proto3" json:"validTime,omitempty"`
	GoodName             string   `protobuf:"bytes,2,opt,name=goodName,proto3" json:"goodName,omitempty"`
	Price                float64  `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ContentId            string   `protobuf:"bytes,5,opt,name=contentId,proto3" json:"contentId,omitempty"`
	ContentToken         string   `protobuf:"bytes,6,opt,name=contentToken,proto3" json:"contentToken,omitempty"`
	UserId               int32    `protobuf:"varint,7,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyInfoCreateRequest) Reset()         { *m = BuyInfoCreateRequest{} }
func (m *BuyInfoCreateRequest) String() string { return proto.CompactTextString(m) }
func (*BuyInfoCreateRequest) ProtoMessage()    {}
func (*BuyInfoCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e8250a94d2d8d95, []int{2}
}

func (m *BuyInfoCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyInfoCreateRequest.Unmarshal(m, b)
}
func (m *BuyInfoCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyInfoCreateRequest.Marshal(b, m, deterministic)
}
func (m *BuyInfoCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyInfoCreateRequest.Merge(m, src)
}
func (m *BuyInfoCreateRequest) XXX_Size() int {
	return xxx_messageInfo_BuyInfoCreateRequest.Size(m)
}
func (m *BuyInfoCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyInfoCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuyInfoCreateRequest proto.InternalMessageInfo

func (m *BuyInfoCreateRequest) GetValidTime() int64 {
	if m != nil {
		return m.ValidTime
	}
	return 0
}

func (m *BuyInfoCreateRequest) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *BuyInfoCreateRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BuyInfoCreateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *BuyInfoCreateRequest) GetContentId() string {
	if m != nil {
		return m.ContentId
	}
	return ""
}

func (m *BuyInfoCreateRequest) GetContentToken() string {
	if m != nil {
		return m.ContentToken
	}
	return ""
}

func (m *BuyInfoCreateRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type BuyInfoCreateResponse struct {
	Status               BuyInfoCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=BuyInfoCreateResponse_Status" json:"status,omitempty"`
	BuyInfoId            int32                        `protobuf:"varint,2,opt,name=buyInfoId,proto3" json:"buyInfoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *BuyInfoCreateResponse) Reset()         { *m = BuyInfoCreateResponse{} }
func (m *BuyInfoCreateResponse) String() string { return proto.CompactTextString(m) }
func (*BuyInfoCreateResponse) ProtoMessage()    {}
func (*BuyInfoCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e8250a94d2d8d95, []int{3}
}

func (m *BuyInfoCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyInfoCreateResponse.Unmarshal(m, b)
}
func (m *BuyInfoCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyInfoCreateResponse.Marshal(b, m, deterministic)
}
func (m *BuyInfoCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyInfoCreateResponse.Merge(m, src)
}
func (m *BuyInfoCreateResponse) XXX_Size() int {
	return xxx_messageInfo_BuyInfoCreateResponse.Size(m)
}
func (m *BuyInfoCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyInfoCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuyInfoCreateResponse proto.InternalMessageInfo

func (m *BuyInfoCreateResponse) GetStatus() BuyInfoCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return BuyInfoCreateResponse_UNKNOWN
}

func (m *BuyInfoCreateResponse) GetBuyInfoId() int32 {
	if m != nil {
		return m.BuyInfoId
	}
	return 0
}

type BuyInfoFindRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	GoodName             string   `protobuf:"bytes,3,opt,name=goodName,proto3" json:"goodName,omitempty"`
	LowPrice             float64  `protobuf:"fixed64,4,opt,name=lowPrice,proto3" json:"lowPrice,omitempty"`
	HighPrice            float64  `protobuf:"fixed64,5,opt,name=highPrice,proto3" json:"highPrice,omitempty"`
	Limit                uint32   `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,7,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyInfoFindRequest) Reset()         { *m = BuyInfoFindRequest{} }
func (m *BuyInfoFindRequest) String() string { return proto.CompactTextString(m) }
func (*BuyInfoFindRequest) ProtoMessage()    {}
func (*BuyInfoFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e8250a94d2d8d95, []int{4}
}

func (m *BuyInfoFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyInfoFindRequest.Unmarshal(m, b)
}
func (m *BuyInfoFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyInfoFindRequest.Marshal(b, m, deterministic)
}
func (m *BuyInfoFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyInfoFindRequest.Merge(m, src)
}
func (m *BuyInfoFindRequest) XXX_Size() int {
	return xxx_messageInfo_BuyInfoFindRequest.Size(m)
}
func (m *BuyInfoFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyInfoFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuyInfoFindRequest proto.InternalMessageInfo

func (m *BuyInfoFindRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BuyInfoFindRequest) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *BuyInfoFindRequest) GetGoodName() string {
	if m != nil {
		return m.GoodName
	}
	return ""
}

func (m *BuyInfoFindRequest) GetLowPrice() float64 {
	if m != nil {
		return m.LowPrice
	}
	return 0
}

func (m *BuyInfoFindRequest) GetHighPrice() float64 {
	if m != nil {
		return m.HighPrice
	}
	return 0
}

func (m *BuyInfoFindRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *BuyInfoFindRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type BuyInfoFindResponse struct {
	BuyInfo              []*BuyInfoMsg `protobuf:"bytes,1,rep,name=buyInfo,proto3" json:"buyInfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *BuyInfoFindResponse) Reset()         { *m = BuyInfoFindResponse{} }
func (m *BuyInfoFindResponse) String() string { return proto.CompactTextString(m) }
func (*BuyInfoFindResponse) ProtoMessage()    {}
func (*BuyInfoFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e8250a94d2d8d95, []int{5}
}

func (m *BuyInfoFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyInfoFindResponse.Unmarshal(m, b)
}
func (m *BuyInfoFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyInfoFindResponse.Marshal(b, m, deterministic)
}
func (m *BuyInfoFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyInfoFindResponse.Merge(m, src)
}
func (m *BuyInfoFindResponse) XXX_Size() int {
	return xxx_messageInfo_BuyInfoFindResponse.Size(m)
}
func (m *BuyInfoFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyInfoFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuyInfoFindResponse proto.InternalMessageInfo

func (m *BuyInfoFindResponse) GetBuyInfo() []*BuyInfoMsg {
	if m != nil {
		return m.BuyInfo
	}
	return nil
}

func init() {
	proto.RegisterEnum("BuyInfoCreateResponse_Status", BuyInfoCreateResponse_Status_name, BuyInfoCreateResponse_Status_value)
	proto.RegisterType((*BuyInfoMsg)(nil), "BuyInfoMsg")
	proto.RegisterType((*BuyInfoQueryRequest)(nil), "BuyInfoQueryRequest")
	proto.RegisterType((*BuyInfoCreateRequest)(nil), "BuyInfoCreateRequest")
	proto.RegisterType((*BuyInfoCreateResponse)(nil), "BuyInfoCreateResponse")
	proto.RegisterType((*BuyInfoFindRequest)(nil), "BuyInfoFindRequest")
	proto.RegisterType((*BuyInfoFindResponse)(nil), "BuyInfoFindResponse")
}

func init() { proto.RegisterFile("buyinfo.proto", fileDescriptor_0e8250a94d2d8d95) }

var fileDescriptor_0e8250a94d2d8d95 = []byte{
	// 555 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x54, 0xdf, 0x8e, 0xd2, 0x4e,
	0x18, 0xfd, 0x0d, 0x50, 0xfe, 0x7c, 0xfc, 0x30, 0x38, 0xcb, 0x6e, 0x9a, 0x46, 0x4d, 0xd3, 0xc4,
	0xa4, 0xf1, 0xa2, 0x89, 0x6c, 0x8c, 0x37, 0xde, 0x20, 0x62, 0xd2, 0xac, 0xdb, 0xdd, 0x1d, 0x58,
	0xbd, 0x34, 0x85, 0x0e, 0x6c, 0x23, 0x74, 0xb0, 0x33, 0xd5, 0xf0, 0x38, 0xde, 0xfb, 0x0e, 0xde,
	0xfa, 0x1c, 0xbe, 0x88, 0x66, 0xa6, 0x85, 0x16, 0xec, 0x62, 0xef, 0xce, 0xf9, 0xbe, 0xf9, 0x73,
	0xce, 0xf9, 0xa6, 0xd0, 0x99, 0x26, 0x9b, 0x30, 0x9a, 0x33, 0x67, 0x1d, 0x33, 0xc1, 0xac, 0xef,
	0x15, 0x80, 0xd7, 0xc9, 0xc6, 0x8d, 0xe6, 0xec, 0x92, 0x2f, 0xf0, 0x23, 0x68, 0x4d, 0x53, 0xe4,
	0x06, 0x3a, 0x32, 0x91, 0xad, 0x91, 0x9c, 0xc0, 0x67, 0x50, 0xe7, 0xc2, 0x17, 0x09, 0xd7, 0x2b,
	0xaa, 0x94, 0x21, 0x6c, 0x42, 0x3b, 0xa6, 0x4b, 0xea, 0x73, 0x3a, 0x09, 0x57, 0x54, 0xaf, 0x9a,
	0xc8, 0xae, 0x92, 0x22, 0x25, 0xf7, 0xfd, 0xe2, 0x2f, 0xc3, 0x40, 0xd5, 0x6b, 0xaa, 0x9e, 0x13,
	0xd8, 0x80, 0xe6, 0x82, 0xb1, 0xc0, 0xf3, 0x57, 0x54, 0xd7, 0x4c, 0x64, 0xb7, 0xc8, 0x0e, 0xe3,
	0x1e, 0x68, 0xeb, 0x38, 0x9c, 0x51, 0xbd, 0x6e, 0x22, 0x1b, 0x91, 0x14, 0xc8, 0x13, 0x03, 0xca,
	0x67, 0x71, 0xb8, 0x16, 0x21, 0x8b, 0xf4, 0x86, 0x5a, 0x54, 0xa4, 0xe4, 0x89, 0x33, 0x16, 0x09,
	0x1a, 0x09, 0x37, 0xd0, 0x9b, 0xaa, 0x9e, 0x13, 0x52, 0x49, 0xc2, 0x69, 0xec, 0x06, 0x7a, 0x2b,
	0x55, 0x92, 0x22, 0xfc, 0x04, 0x60, 0xb6, 0xa4, 0x7e, 0x3c, 0x5a, 0xad, 0xc5, 0x46, 0x9f, 0x99,
	0xc8, 0x6e, 0x92, 0x02, 0x63, 0x9d, 0xc3, 0x49, 0xe6, 0xd6, 0x4d, 0x42, 0xe3, 0x0d, 0xa1, 0x9f,
	0x13, 0xca, 0xc5, 0x71, 0xdb, 0xac, 0x5f, 0x08, 0x7a, 0xd9, 0xaa, 0x61, 0x4c, 0x7d, 0x41, 0x0b,
	0xcb, 0x72, 0x57, 0xd0, 0x31, 0x57, 0x2a, 0xf7, 0xb9, 0x52, 0x3d, 0xe2, 0x4a, 0xed, 0x1f, 0xae,
	0x68, 0x87, 0xae, 0x58, 0xf0, 0x7f, 0x06, 0x26, 0xec, 0x13, 0x8d, 0x94, 0xe5, 0x2d, 0xb2, 0xc7,
	0x15, 0x9c, 0x6b, 0x14, 0x9d, 0xb3, 0x7e, 0x20, 0x38, 0x3d, 0x10, 0xc9, 0xd7, 0x2c, 0xe2, 0x14,
	0xbf, 0xd8, 0x4d, 0x8d, 0x94, 0xf8, 0xa0, 0xff, 0xd8, 0x29, 0xed, 0x73, 0xc6, 0xaa, 0x69, 0x37,
	0x54, 0x7b, 0x9e, 0x56, 0x0e, 0x3d, 0xbd, 0x81, 0x7a, 0xda, 0x8f, 0xdb, 0xd0, 0xb8, 0xf5, 0x2e,
	0xbc, 0xab, 0x0f, 0x5e, 0xf7, 0x3f, 0x6c, 0x40, 0xc7, 0xf5, 0xde, 0x0f, 0xde, 0xb9, 0x6f, 0x3e,
	0x5e, 0x0f, 0xc8, 0xe0, 0xb2, 0xfb, 0x7b, 0xfb, 0x21, 0xd9, 0x38, 0xbe, 0x1d, 0x0e, 0x47, 0xe3,
	0x71, 0x17, 0xe1, 0x87, 0x79, 0xe3, 0xe4, 0xea, 0x62, 0xe4, 0x75, 0x2b, 0xd6, 0x4f, 0x04, 0x38,
	0xbb, 0xd9, 0xdb, 0x30, 0x0a, 0xb6, 0x21, 0xe5, 0x82, 0xd1, 0xde, 0xa8, 0xdc, 0xf7, 0x18, 0x8a,
	0xb1, 0x55, 0x0f, 0x62, 0x33, 0xa0, 0xb9, 0x64, 0x5f, 0xaf, 0x55, 0x72, 0x35, 0x95, 0xdc, 0x0e,
	0x4b, 0xbd, 0x77, 0xe1, 0xe2, 0x2e, 0x2d, 0x6a, 0xaa, 0x98, 0x13, 0x32, 0xf0, 0x65, 0xb8, 0x0a,
	0x85, 0xca, 0xa4, 0x43, 0x52, 0x20, 0xef, 0xc0, 0xe6, 0x73, 0x4e, 0x85, 0x0a, 0xa3, 0x43, 0x32,
	0x64, 0xbd, 0xda, 0x8d, 0x69, 0xaa, 0x24, 0x4b, 0xe2, 0x29, 0x34, 0x32, 0x07, 0x75, 0x64, 0x56,
	0xed, 0x76, 0xbf, 0xed, 0xe4, 0x6f, 0x9f, 0x6c, 0x6b, 0xfd, 0x6f, 0x08, 0x1a, 0x19, 0x8f, 0x9f,
	0x81, 0xa6, 0x26, 0x1d, 0xf7, 0x9c, 0x92, 0xc1, 0x37, 0x8a, 0x1b, 0xe0, 0x97, 0x50, 0x4f, 0x23,
	0xc5, 0xa7, 0x4e, 0xd9, 0xbc, 0x1b, 0x67, 0xe5, 0xc9, 0xe3, 0xe7, 0x50, 0x93, 0xf7, 0xc4, 0x27,
	0xce, 0xdf, 0xfe, 0x1b, 0x3d, 0xa7, 0x44, 0xca, 0xb4, 0xae, 0x7e, 0x5f, 0xe7, 0x7f, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x72, 0x9f, 0x60, 0x06, 0xcf, 0x04, 0x00, 0x00,
}
