// Code generated by protoc-gen-go. DO NOT EDIT.
// source: transaction.proto

package transaction

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TransStatus int32

const (
	TransStatus_UNKNOWN  TransStatus = 0
	TransStatus_ASKING   TransStatus = 1
	TransStatus_ACCEPTED TransStatus = 2
	TransStatus_REJECTED TransStatus = 3
	TransStatus_CLOSED   TransStatus = 4
	TransStatus_PENDING  TransStatus = 5
	TransStatus_DONE     TransStatus = 6
)

var TransStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "ASKING",
	2: "ACCEPTED",
	3: "REJECTED",
	4: "CLOSED",
	5: "PENDING",
	6: "DONE",
}

var TransStatus_value = map[string]int32{
	"UNKNOWN":  0,
	"ASKING":   1,
	"ACCEPTED": 2,
	"REJECTED": 3,
	"CLOSED":   4,
	"PENDING":  5,
	"DONE":     6,
}

func (x TransStatus) String() string {
	return proto.EnumName(TransStatus_name, int32(x))
}

func (TransStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

type TransactionCreateRequest_Category int32

const (
	TransactionCreateRequest_UNKNOWN TransactionCreateRequest_Category = 0
	TransactionCreateRequest_SELL    TransactionCreateRequest_Category = 1
	TransactionCreateRequest_BUY     TransactionCreateRequest_Category = 2
)

var TransactionCreateRequest_Category_name = map[int32]string{
	0: "UNKNOWN",
	1: "SELL",
	2: "BUY",
}

var TransactionCreateRequest_Category_value = map[string]int32{
	"UNKNOWN": 0,
	"SELL":    1,
	"BUY":     2,
}

func (x TransactionCreateRequest_Category) String() string {
	return proto.EnumName(TransactionCreateRequest_Category_name, int32(x))
}

func (TransactionCreateRequest_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0, 0}
}

type TransactionCreateResponse_Status int32

const (
	TransactionCreateResponse_UNKNOWN       TransactionCreateResponse_Status = 0
	TransactionCreateResponse_INVALID_PARAM TransactionCreateResponse_Status = -1
	TransactionCreateResponse_SUCCESS       TransactionCreateResponse_Status = 1
)

var TransactionCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
}

var TransactionCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
}

func (x TransactionCreateResponse_Status) String() string {
	return proto.EnumName(TransactionCreateResponse_Status_name, int32(x))
}

func (TransactionCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1, 0}
}

type TransactionUpdateResponse_Status int32

const (
	TransactionUpdateResponse_UNKNOWN       TransactionUpdateResponse_Status = 0
	TransactionUpdateResponse_INVALID_PARAM TransactionUpdateResponse_Status = -1
	TransactionUpdateResponse_SUCCESS       TransactionUpdateResponse_Status = 1
	TransactionUpdateResponse_NOT_FOUND     TransactionUpdateResponse_Status = 2
)

var TransactionUpdateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "NOT_FOUND",
}

var TransactionUpdateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"NOT_FOUND":     2,
}

func (x TransactionUpdateResponse_Status) String() string {
	return proto.EnumName(TransactionUpdateResponse_Status_name, int32(x))
}

func (TransactionUpdateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3, 0}
}

type TransactionMsg_Category int32

const (
	TransactionMsg_CATEGORY_UNKNOWN TransactionMsg_Category = 0
	TransactionMsg_SELL             TransactionMsg_Category = 1
	TransactionMsg_BUY              TransactionMsg_Category = 2
)

var TransactionMsg_Category_name = map[int32]string{
	0: "CATEGORY_UNKNOWN",
	1: "SELL",
	2: "BUY",
}

var TransactionMsg_Category_value = map[string]int32{
	"CATEGORY_UNKNOWN": 0,
	"SELL":             1,
	"BUY":              2,
}

func (x TransactionMsg_Category) String() string {
	return proto.EnumName(TransactionMsg_Category_name, int32(x))
}

func (TransactionMsg_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4, 0}
}

type TransactionFindRequest_Category int32

const (
	TransactionFindRequest_CATEGORY_UNKNOWN TransactionFindRequest_Category = 0
	TransactionFindRequest_SELL             TransactionFindRequest_Category = 1
	TransactionFindRequest_BUY              TransactionFindRequest_Category = 2
)

var TransactionFindRequest_Category_name = map[int32]string{
	0: "CATEGORY_UNKNOWN",
	1: "SELL",
	2: "BUY",
}

var TransactionFindRequest_Category_value = map[string]int32{
	"CATEGORY_UNKNOWN": 0,
	"SELL":             1,
	"BUY":              2,
}

func (x TransactionFindRequest_Category) String() string {
	return proto.EnumName(TransactionFindRequest_Category_name, int32(x))
}

func (TransactionFindRequest_Category) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5, 0}
}

type TransactionFindResponse_Status int32

const (
	TransactionFindResponse_UNKNOWN       TransactionFindResponse_Status = 0
	TransactionFindResponse_INVALID_PARAM TransactionFindResponse_Status = -1
	TransactionFindResponse_SUCCESS       TransactionFindResponse_Status = 1
	TransactionFindResponse_NOT_FOUND     TransactionFindResponse_Status = 2
)

var TransactionFindResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "NOT_FOUND",
}

var TransactionFindResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"NOT_FOUND":     2,
}

func (x TransactionFindResponse_Status) String() string {
	return proto.EnumName(TransactionFindResponse_Status_name, int32(x))
}

func (TransactionFindResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{6, 0}
}

type TransactionCreateRequest struct {
	InfoID               int32                             `protobuf:"varint,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Category             TransactionCreateRequest_Category `protobuf:"varint,2,opt,name=category,proto3,enum=TransactionCreateRequest_Category" json:"category,omitempty"`
	UserID               int32                             `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *TransactionCreateRequest) Reset()         { *m = TransactionCreateRequest{} }
func (m *TransactionCreateRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionCreateRequest) ProtoMessage()    {}
func (*TransactionCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{0}
}

func (m *TransactionCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionCreateRequest.Unmarshal(m, b)
}
func (m *TransactionCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionCreateRequest.Marshal(b, m, deterministic)
}
func (m *TransactionCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionCreateRequest.Merge(m, src)
}
func (m *TransactionCreateRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionCreateRequest.Size(m)
}
func (m *TransactionCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionCreateRequest proto.InternalMessageInfo

func (m *TransactionCreateRequest) GetInfoID() int32 {
	if m != nil {
		return m.InfoID
	}
	return 0
}

func (m *TransactionCreateRequest) GetCategory() TransactionCreateRequest_Category {
	if m != nil {
		return m.Category
	}
	return TransactionCreateRequest_UNKNOWN
}

func (m *TransactionCreateRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type TransactionCreateResponse struct {
	Status               TransactionCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=TransactionCreateResponse_Status" json:"status,omitempty"`
	TransactionID        int32                            `protobuf:"varint,2,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TransactionCreateResponse) Reset()         { *m = TransactionCreateResponse{} }
func (m *TransactionCreateResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionCreateResponse) ProtoMessage()    {}
func (*TransactionCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{1}
}

func (m *TransactionCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionCreateResponse.Unmarshal(m, b)
}
func (m *TransactionCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionCreateResponse.Marshal(b, m, deterministic)
}
func (m *TransactionCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionCreateResponse.Merge(m, src)
}
func (m *TransactionCreateResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionCreateResponse.Size(m)
}
func (m *TransactionCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionCreateResponse proto.InternalMessageInfo

func (m *TransactionCreateResponse) GetStatus() TransactionCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return TransactionCreateResponse_UNKNOWN
}

func (m *TransactionCreateResponse) GetTransactionID() int32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

type TransactionUpdateRequest struct {
	TransactionID        int32       `protobuf:"varint,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	Status               TransStatus `protobuf:"varint,2,opt,name=status,proto3,enum=TransStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TransactionUpdateRequest) Reset()         { *m = TransactionUpdateRequest{} }
func (m *TransactionUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionUpdateRequest) ProtoMessage()    {}
func (*TransactionUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{2}
}

func (m *TransactionUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionUpdateRequest.Unmarshal(m, b)
}
func (m *TransactionUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionUpdateRequest.Marshal(b, m, deterministic)
}
func (m *TransactionUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionUpdateRequest.Merge(m, src)
}
func (m *TransactionUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionUpdateRequest.Size(m)
}
func (m *TransactionUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionUpdateRequest proto.InternalMessageInfo

func (m *TransactionUpdateRequest) GetTransactionID() int32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

func (m *TransactionUpdateRequest) GetStatus() TransStatus {
	if m != nil {
		return m.Status
	}
	return TransStatus_UNKNOWN
}

type TransactionUpdateResponse struct {
	Status               TransactionUpdateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=TransactionUpdateResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TransactionUpdateResponse) Reset()         { *m = TransactionUpdateResponse{} }
func (m *TransactionUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionUpdateResponse) ProtoMessage()    {}
func (*TransactionUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{3}
}

func (m *TransactionUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionUpdateResponse.Unmarshal(m, b)
}
func (m *TransactionUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionUpdateResponse.Marshal(b, m, deterministic)
}
func (m *TransactionUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionUpdateResponse.Merge(m, src)
}
func (m *TransactionUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionUpdateResponse.Size(m)
}
func (m *TransactionUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionUpdateResponse proto.InternalMessageInfo

func (m *TransactionUpdateResponse) GetStatus() TransactionUpdateResponse_Status {
	if m != nil {
		return m.Status
	}
	return TransactionUpdateResponse_UNKNOWN
}

type TransactionMsg struct {
	TransactionID        int32                   `protobuf:"varint,1,opt,name=transactionID,proto3" json:"transactionID,omitempty"`
	InfoID               int32                   `protobuf:"varint,2,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Category             TransactionMsg_Category `protobuf:"varint,3,opt,name=category,proto3,enum=TransactionMsg_Category" json:"category,omitempty"`
	UserID               int32                   `protobuf:"varint,4,opt,name=userID,proto3" json:"userID,omitempty"`
	CreateTime           int64                   `protobuf:"varint,5,opt,name=createTime,proto3" json:"createTime,omitempty"`
	Status               TransStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=TransStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *TransactionMsg) Reset()         { *m = TransactionMsg{} }
func (m *TransactionMsg) String() string { return proto.CompactTextString(m) }
func (*TransactionMsg) ProtoMessage()    {}
func (*TransactionMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{4}
}

func (m *TransactionMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionMsg.Unmarshal(m, b)
}
func (m *TransactionMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionMsg.Marshal(b, m, deterministic)
}
func (m *TransactionMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionMsg.Merge(m, src)
}
func (m *TransactionMsg) XXX_Size() int {
	return xxx_messageInfo_TransactionMsg.Size(m)
}
func (m *TransactionMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionMsg.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionMsg proto.InternalMessageInfo

func (m *TransactionMsg) GetTransactionID() int32 {
	if m != nil {
		return m.TransactionID
	}
	return 0
}

func (m *TransactionMsg) GetInfoID() int32 {
	if m != nil {
		return m.InfoID
	}
	return 0
}

func (m *TransactionMsg) GetCategory() TransactionMsg_Category {
	if m != nil {
		return m.Category
	}
	return TransactionMsg_CATEGORY_UNKNOWN
}

func (m *TransactionMsg) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *TransactionMsg) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *TransactionMsg) GetStatus() TransStatus {
	if m != nil {
		return m.Status
	}
	return TransStatus_UNKNOWN
}

type TransactionFindRequest struct {
	InfoID               int32                           `protobuf:"varint,1,opt,name=infoID,proto3" json:"infoID,omitempty"`
	Category             TransactionFindRequest_Category `protobuf:"varint,2,opt,name=category,proto3,enum=TransactionFindRequest_Category" json:"category,omitempty"`
	UserID               int32                           `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	LowCreateTime        int64                           `protobuf:"varint,4,opt,name=lowCreateTime,proto3" json:"lowCreateTime,omitempty"`
	HighCreateTime       int64                           `protobuf:"varint,5,opt,name=highCreateTime,proto3" json:"highCreateTime,omitempty"`
	Status               TransStatus                     `protobuf:"varint,6,opt,name=status,proto3,enum=TransStatus" json:"status,omitempty"`
	Limit                uint32                          `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32                          `protobuf:"varint,8,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                        `json:"-"`
	XXX_unrecognized     []byte                          `json:"-"`
	XXX_sizecache        int32                           `json:"-"`
}

func (m *TransactionFindRequest) Reset()         { *m = TransactionFindRequest{} }
func (m *TransactionFindRequest) String() string { return proto.CompactTextString(m) }
func (*TransactionFindRequest) ProtoMessage()    {}
func (*TransactionFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{5}
}

func (m *TransactionFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionFindRequest.Unmarshal(m, b)
}
func (m *TransactionFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionFindRequest.Marshal(b, m, deterministic)
}
func (m *TransactionFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionFindRequest.Merge(m, src)
}
func (m *TransactionFindRequest) XXX_Size() int {
	return xxx_messageInfo_TransactionFindRequest.Size(m)
}
func (m *TransactionFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionFindRequest proto.InternalMessageInfo

func (m *TransactionFindRequest) GetInfoID() int32 {
	if m != nil {
		return m.InfoID
	}
	return 0
}

func (m *TransactionFindRequest) GetCategory() TransactionFindRequest_Category {
	if m != nil {
		return m.Category
	}
	return TransactionFindRequest_CATEGORY_UNKNOWN
}

func (m *TransactionFindRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *TransactionFindRequest) GetLowCreateTime() int64 {
	if m != nil {
		return m.LowCreateTime
	}
	return 0
}

func (m *TransactionFindRequest) GetHighCreateTime() int64 {
	if m != nil {
		return m.HighCreateTime
	}
	return 0
}

func (m *TransactionFindRequest) GetStatus() TransStatus {
	if m != nil {
		return m.Status
	}
	return TransStatus_UNKNOWN
}

func (m *TransactionFindRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *TransactionFindRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type TransactionFindResponse struct {
	Status               TransactionFindResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=TransactionFindResponse_Status" json:"status,omitempty"`
	Transactions         []*TransactionMsg              `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *TransactionFindResponse) Reset()         { *m = TransactionFindResponse{} }
func (m *TransactionFindResponse) String() string { return proto.CompactTextString(m) }
func (*TransactionFindResponse) ProtoMessage()    {}
func (*TransactionFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2cc4e03d2c28c490, []int{6}
}

func (m *TransactionFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TransactionFindResponse.Unmarshal(m, b)
}
func (m *TransactionFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TransactionFindResponse.Marshal(b, m, deterministic)
}
func (m *TransactionFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TransactionFindResponse.Merge(m, src)
}
func (m *TransactionFindResponse) XXX_Size() int {
	return xxx_messageInfo_TransactionFindResponse.Size(m)
}
func (m *TransactionFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TransactionFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TransactionFindResponse proto.InternalMessageInfo

func (m *TransactionFindResponse) GetStatus() TransactionFindResponse_Status {
	if m != nil {
		return m.Status
	}
	return TransactionFindResponse_UNKNOWN
}

func (m *TransactionFindResponse) GetTransactions() []*TransactionMsg {
	if m != nil {
		return m.Transactions
	}
	return nil
}

func init() {
	proto.RegisterEnum("TransStatus", TransStatus_name, TransStatus_value)
	proto.RegisterEnum("TransactionCreateRequest_Category", TransactionCreateRequest_Category_name, TransactionCreateRequest_Category_value)
	proto.RegisterEnum("TransactionCreateResponse_Status", TransactionCreateResponse_Status_name, TransactionCreateResponse_Status_value)
	proto.RegisterEnum("TransactionUpdateResponse_Status", TransactionUpdateResponse_Status_name, TransactionUpdateResponse_Status_value)
	proto.RegisterEnum("TransactionMsg_Category", TransactionMsg_Category_name, TransactionMsg_Category_value)
	proto.RegisterEnum("TransactionFindRequest_Category", TransactionFindRequest_Category_name, TransactionFindRequest_Category_value)
	proto.RegisterEnum("TransactionFindResponse_Status", TransactionFindResponse_Status_name, TransactionFindResponse_Status_value)
	proto.RegisterType((*TransactionCreateRequest)(nil), "TransactionCreateRequest")
	proto.RegisterType((*TransactionCreateResponse)(nil), "TransactionCreateResponse")
	proto.RegisterType((*TransactionUpdateRequest)(nil), "TransactionUpdateRequest")
	proto.RegisterType((*TransactionUpdateResponse)(nil), "TransactionUpdateResponse")
	proto.RegisterType((*TransactionMsg)(nil), "TransactionMsg")
	proto.RegisterType((*TransactionFindRequest)(nil), "TransactionFindRequest")
	proto.RegisterType((*TransactionFindResponse)(nil), "TransactionFindResponse")
}

func init() { proto.RegisterFile("transaction.proto", fileDescriptor_2cc4e03d2c28c490) }

var fileDescriptor_2cc4e03d2c28c490 = []byte{
	// 632 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0xdd, 0x8e, 0xd2, 0x50,
	0x10, 0xf6, 0xb4, 0x50, 0x70, 0xf8, 0xb1, 0x9e, 0x6c, 0x76, 0xbb, 0x5c, 0x28, 0x36, 0x1b, 0x43,
	0xf6, 0xa2, 0x17, 0x60, 0x62, 0x4c, 0xcc, 0x9a, 0xda, 0x76, 0x37, 0x75, 0xa1, 0x25, 0x2d, 0x68,
	0xf6, 0x8a, 0x20, 0x5b, 0xd8, 0x26, 0xbb, 0x14, 0x69, 0x89, 0xf1, 0x49, 0x7c, 0x02, 0x5f, 0xc1,
	0x2b, 0x9f, 0xc0, 0x07, 0xf0, 0xce, 0x67, 0xd1, 0x9c, 0xb6, 0x2c, 0x3d, 0x85, 0x22, 0xea, 0xf6,
	0x6e, 0x26, 0x73, 0xbe, 0x99, 0xf9, 0xe6, 0x9b, 0x29, 0x3c, 0x0c, 0xe6, 0xc3, 0xa9, 0x3f, 0x1c,
	0x05, 0xae, 0x37, 0x95, 0x66, 0x73, 0x2f, 0xf0, 0xc4, 0xaf, 0x08, 0x84, 0xde, 0xca, 0xab, 0xcc,
	0x9d, 0x61, 0xe0, 0x58, 0xce, 0x87, 0x85, 0xe3, 0x07, 0x78, 0x1f, 0x38, 0x77, 0x3a, 0xf6, 0x74,
	0x55, 0x40, 0x75, 0xd4, 0xc8, 0x5b, 0xb1, 0x85, 0x4f, 0xa0, 0x38, 0x1a, 0x06, 0xce, 0xc4, 0x9b,
	0x7f, 0x12, 0x98, 0x3a, 0x6a, 0x54, 0x9b, 0xa2, 0x94, 0x05, 0x22, 0x29, 0x71, 0xa4, 0x75, 0xfb,
	0x86, 0xe0, 0x2e, 0x7c, 0x67, 0xae, 0xab, 0x02, 0x1b, 0xe1, 0x46, 0x96, 0x78, 0x0c, 0xc5, 0x65,
	0x34, 0x2e, 0x41, 0xa1, 0x6f, 0x9c, 0x1b, 0xe6, 0x3b, 0x83, 0xbf, 0x87, 0x8b, 0x90, 0xb3, 0xb5,
	0x76, 0x9b, 0x47, 0xb8, 0x00, 0xec, 0xeb, 0xfe, 0x05, 0xcf, 0x88, 0xdf, 0x10, 0x1c, 0x6e, 0xc8,
	0xe9, 0xcf, 0xbc, 0xa9, 0xef, 0xe0, 0x17, 0xc0, 0xf9, 0xc1, 0x30, 0x58, 0xf8, 0x61, 0xe5, 0xd5,
	0xe6, 0x13, 0x29, 0x33, 0x56, 0xb2, 0xc3, 0x40, 0x2b, 0x7e, 0x80, 0x8f, 0xa0, 0x92, 0xa0, 0x49,
	0x57, 0xc3, 0x0e, 0xf3, 0x16, 0xed, 0x14, 0x4f, 0x80, 0x8b, 0xde, 0xd1, 0x85, 0xd6, 0xa0, 0xa2,
	0x1b, 0x6f, 0xe5, 0xb6, 0xae, 0x0e, 0xba, 0xb2, 0x25, 0x77, 0xf8, 0x5f, 0xcb, 0x0f, 0x91, 0x40,
	0xbb, 0xaf, 0x28, 0x9a, 0x6d, 0xf3, 0x48, 0x1c, 0x53, 0xb4, 0xf7, 0x67, 0x97, 0x09, 0xda, 0xd7,
	0x2a, 0x40, 0x1b, 0x2a, 0xc0, 0x47, 0xb7, 0x2d, 0x46, 0x23, 0x28, 0x47, 0x2d, 0xd2, 0xdd, 0x88,
	0x5f, 0x68, 0x9a, 0x96, 0x89, 0x76, 0xa1, 0x89, 0x8e, 0x4d, 0xd1, 0x24, 0x76, 0xfe, 0x8f, 0x00,
	0x5c, 0x81, 0xfb, 0x86, 0xd9, 0x1b, 0x9c, 0x9a, 0x7d, 0x43, 0xe5, 0x19, 0xf1, 0x33, 0x03, 0xd5,
	0x44, 0xee, 0x8e, 0x3f, 0xd9, 0x91, 0x86, 0x95, 0x46, 0x19, 0x4a, 0xa3, 0xcf, 0x12, 0x1a, 0x65,
	0xc3, 0xe6, 0x04, 0x89, 0x4e, 0xb0, 0x5d, 0x99, 0xb9, 0xa4, 0x32, 0xf1, 0x23, 0x80, 0x51, 0xa8,
	0x9a, 0x9e, 0x7b, 0xe3, 0x08, 0xf9, 0x3a, 0x6a, 0xb0, 0x56, 0xc2, 0x93, 0x18, 0x06, 0xb7, 0x65,
	0x18, 0xad, 0x84, 0xbe, 0xf7, 0x80, 0x57, 0xe4, 0x9e, 0x76, 0x66, 0x5a, 0x17, 0x83, 0xad, 0x42,
	0xff, 0xc9, 0xc0, 0x7e, 0xa2, 0xf0, 0x53, 0x77, 0x7a, 0xf9, 0xa7, 0xfd, 0x7c, 0xb9, 0xb6, 0x9f,
	0x75, 0x69, 0x33, 0xc4, 0x5f, 0x6c, 0x27, 0x99, 0xc7, 0xb5, 0xf7, 0x51, 0x59, 0xd1, 0x90, 0x0b,
	0x69, 0xa0, 0x9d, 0xf8, 0x29, 0x54, 0xaf, 0xdc, 0xc9, 0x95, 0x92, 0x66, 0x2b, 0xe5, 0xdd, 0x8d,
	0x31, 0xbc, 0x07, 0xf9, 0x6b, 0xf7, 0xc6, 0x0d, 0x84, 0x42, 0x1d, 0x35, 0x2a, 0x56, 0x64, 0x90,
	0x0a, 0xbd, 0xf1, 0xd8, 0x77, 0x02, 0xa1, 0x18, 0xba, 0x63, 0xeb, 0xdf, 0xf8, 0xfd, 0x81, 0xe0,
	0x60, 0x8d, 0x9c, 0x78, 0x3f, 0x9e, 0xa7, 0xf6, 0xe3, 0xb1, 0x94, 0x11, 0x99, 0x3e, 0x22, 0x2d,
	0x28, 0x27, 0x64, 0x4a, 0x56, 0x94, 0x6d, 0x94, 0x9a, 0x0f, 0x52, 0x0a, 0xb4, 0xa8, 0xa0, 0x3b,
	0x5e, 0xa9, 0x63, 0x07, 0x4a, 0x09, 0x4a, 0x69, 0x4c, 0x00, 0x4e, 0xb6, 0xcf, 0x75, 0xe3, 0x8c,
	0x47, 0xb8, 0x0c, 0x45, 0x59, 0x51, 0xb4, 0x6e, 0x4f, 0x53, 0x79, 0x86, 0x58, 0x96, 0xf6, 0x46,
	0x53, 0x88, 0xc5, 0x92, 0x38, 0xa5, 0x6d, 0xda, 0x9a, 0xca, 0xe7, 0x08, 0x40, 0x57, 0x33, 0x54,
	0xf2, 0x28, 0x4f, 0x88, 0x54, 0x4d, 0x43, 0xe3, 0xb9, 0xe6, 0x77, 0x14, 0xe7, 0x89, 0xda, 0xc0,
	0xaf, 0x80, 0x8b, 0xc6, 0x8c, 0x0f, 0x33, 0x7f, 0x0a, 0xb5, 0x5a, 0xf6, 0x3d, 0x26, 0x00, 0xd1,
	0xe9, 0xa1, 0x01, 0xa8, 0x1b, 0x49, 0x03, 0xac, 0x5d, 0xb5, 0x1c, 0x99, 0x0d, 0x3e, 0xc8, 0x10,
	0x7d, 0x4d, 0xc8, 0x1a, 0xe3, 0x7b, 0x2e, 0xfc, 0x2b, 0xb6, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xab, 0xe3, 0xee, 0xdb, 0x2a, 0x07, 0x00, 0x00,
}
