// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_UNKNOWN Type = 0
	Type_TEXT    Type = 1
	Type_PICTURE Type = 2
	Type_VIDEO   Type = 3
)

var Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "TEXT",
	2: "PICTURE",
	3: "VIDEO",
}

var Type_value = map[string]int32{
	"UNKNOWN": 0,
	"TEXT":    1,
	"PICTURE": 2,
	"VIDEO":   3,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type MessageCreateResponse_Status int32

const (
	MessageCreateResponse_UNKNOWN       MessageCreateResponse_Status = 0
	MessageCreateResponse_INVALID_PARAM MessageCreateResponse_Status = -1
	MessageCreateResponse_SUCCESS       MessageCreateResponse_Status = 1
	MessageCreateResponse_INVALID_TYPE  MessageCreateResponse_Status = 2
)

var MessageCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "INVALID_TYPE",
}

var MessageCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"INVALID_TYPE":  2,
}

func (x MessageCreateResponse_Status) String() string {
	return proto.EnumName(MessageCreateResponse_Status_name, int32(x))
}

func (MessageCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2, 0}
}

type MessageFindRequest_Way int32

const (
	MessageFindRequest_UNKNOWN      MessageFindRequest_Way = 0
	MessageFindRequest_READ_MESSAGE MessageFindRequest_Way = 1
	MessageFindRequest_HISTORY      MessageFindRequest_Way = 2
)

var MessageFindRequest_Way_name = map[int32]string{
	0: "UNKNOWN",
	1: "READ_MESSAGE",
	2: "HISTORY",
}

var MessageFindRequest_Way_value = map[string]int32{
	"UNKNOWN":      0,
	"READ_MESSAGE": 1,
	"HISTORY":      2,
}

func (x MessageFindRequest_Way) String() string {
	return proto.EnumName(MessageFindRequest_Way_name, int32(x))
}

func (MessageFindRequest_Way) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3, 0}
}

type MessageFindResponse_Status int32

const (
	MessageFindResponse_UNKNOWN       MessageFindResponse_Status = 0
	MessageFindResponse_INVALID_PARAM MessageFindResponse_Status = -1
	MessageFindResponse_SUCCESS       MessageFindResponse_Status = 1
)

var MessageFindResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
}

var MessageFindResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
}

func (x MessageFindResponse_Status) String() string {
	return proto.EnumName(MessageFindResponse_Status_name, int32(x))
}

func (MessageFindResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4, 0}
}

type MessageQueryResponse_Status int32

const (
	MessageQueryResponse_UNKNOWN       MessageQueryResponse_Status = 0
	MessageQueryResponse_INVALID_PARAM MessageQueryResponse_Status = -1
	MessageQueryResponse_SUCCESS       MessageQueryResponse_Status = 1
)

var MessageQueryResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
}

var MessageQueryResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
}

func (x MessageQueryResponse_Status) String() string {
	return proto.EnumName(MessageQueryResponse_Status_name, int32(x))
}

func (MessageQueryResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7, 0}
}

type MessageInfo struct {
	Time                 int64    `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Forward              bool     `protobuf:"varint,2,opt,name=forward,proto3" json:"forward,omitempty"`
	Type                 Type     `protobuf:"varint,3,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	Msg                  string   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	Unread               bool     `protobuf:"varint,5,opt,name=unread,proto3" json:"unread,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageInfo) Reset()         { *m = MessageInfo{} }
func (m *MessageInfo) String() string { return proto.CompactTextString(m) }
func (*MessageInfo) ProtoMessage()    {}
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *MessageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInfo.Unmarshal(m, b)
}
func (m *MessageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInfo.Marshal(b, m, deterministic)
}
func (m *MessageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInfo.Merge(m, src)
}
func (m *MessageInfo) XXX_Size() int {
	return xxx_messageInfo_MessageInfo.Size(m)
}
func (m *MessageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInfo proto.InternalMessageInfo

func (m *MessageInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *MessageInfo) GetForward() bool {
	if m != nil {
		return m.Forward
	}
	return false
}

func (m *MessageInfo) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_UNKNOWN
}

func (m *MessageInfo) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *MessageInfo) GetUnread() bool {
	if m != nil {
		return m.Unread
	}
	return false
}

type MessageCreateRequest struct {
	FromUser             int32    `protobuf:"varint,1,opt,name=fromUser,proto3" json:"fromUser,omitempty"`
	ToUser               int32    `protobuf:"varint,2,opt,name=toUser,proto3" json:"toUser,omitempty"`
	Type                 Type     `protobuf:"varint,3,opt,name=type,proto3,enum=Type" json:"type,omitempty"`
	Msg                  []byte   `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageCreateRequest) Reset()         { *m = MessageCreateRequest{} }
func (m *MessageCreateRequest) String() string { return proto.CompactTextString(m) }
func (*MessageCreateRequest) ProtoMessage()    {}
func (*MessageCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *MessageCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCreateRequest.Unmarshal(m, b)
}
func (m *MessageCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCreateRequest.Marshal(b, m, deterministic)
}
func (m *MessageCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCreateRequest.Merge(m, src)
}
func (m *MessageCreateRequest) XXX_Size() int {
	return xxx_messageInfo_MessageCreateRequest.Size(m)
}
func (m *MessageCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCreateRequest proto.InternalMessageInfo

func (m *MessageCreateRequest) GetFromUser() int32 {
	if m != nil {
		return m.FromUser
	}
	return 0
}

func (m *MessageCreateRequest) GetToUser() int32 {
	if m != nil {
		return m.ToUser
	}
	return 0
}

func (m *MessageCreateRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_UNKNOWN
}

func (m *MessageCreateRequest) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

type MessageCreateResponse struct {
	Status               MessageCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=MessageCreateResponse_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *MessageCreateResponse) Reset()         { *m = MessageCreateResponse{} }
func (m *MessageCreateResponse) String() string { return proto.CompactTextString(m) }
func (*MessageCreateResponse) ProtoMessage()    {}
func (*MessageCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *MessageCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageCreateResponse.Unmarshal(m, b)
}
func (m *MessageCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageCreateResponse.Marshal(b, m, deterministic)
}
func (m *MessageCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageCreateResponse.Merge(m, src)
}
func (m *MessageCreateResponse) XXX_Size() int {
	return xxx_messageInfo_MessageCreateResponse.Size(m)
}
func (m *MessageCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageCreateResponse proto.InternalMessageInfo

func (m *MessageCreateResponse) GetStatus() MessageCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return MessageCreateResponse_UNKNOWN
}

type MessageFindRequest struct {
	FromUser             int32                  `protobuf:"varint,1,opt,name=fromUser,proto3" json:"fromUser,omitempty"`
	ToUser               int32                  `protobuf:"varint,2,opt,name=toUser,proto3" json:"toUser,omitempty"`
	Way                  MessageFindRequest_Way `protobuf:"varint,3,opt,name=way,proto3,enum=MessageFindRequest_Way" json:"way,omitempty"`
	Limit                uint32                 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32                 `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *MessageFindRequest) Reset()         { *m = MessageFindRequest{} }
func (m *MessageFindRequest) String() string { return proto.CompactTextString(m) }
func (*MessageFindRequest) ProtoMessage()    {}
func (*MessageFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *MessageFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageFindRequest.Unmarshal(m, b)
}
func (m *MessageFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageFindRequest.Marshal(b, m, deterministic)
}
func (m *MessageFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageFindRequest.Merge(m, src)
}
func (m *MessageFindRequest) XXX_Size() int {
	return xxx_messageInfo_MessageFindRequest.Size(m)
}
func (m *MessageFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageFindRequest proto.InternalMessageInfo

func (m *MessageFindRequest) GetFromUser() int32 {
	if m != nil {
		return m.FromUser
	}
	return 0
}

func (m *MessageFindRequest) GetToUser() int32 {
	if m != nil {
		return m.ToUser
	}
	return 0
}

func (m *MessageFindRequest) GetWay() MessageFindRequest_Way {
	if m != nil {
		return m.Way
	}
	return MessageFindRequest_UNKNOWN
}

func (m *MessageFindRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *MessageFindRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

type MessageFindResponse struct {
	Status               MessageFindResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=MessageFindResponse_Status" json:"status,omitempty"`
	FromUser             int32                      `protobuf:"varint,2,opt,name=fromUser,proto3" json:"fromUser,omitempty"`
	ToUser               int32                      `protobuf:"varint,3,opt,name=toUser,proto3" json:"toUser,omitempty"`
	Badge                int32                      `protobuf:"varint,4,opt,name=badge,proto3" json:"badge,omitempty"`
	Infos                []*MessageInfo             `protobuf:"bytes,5,rep,name=infos,proto3" json:"infos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                   `json:"-"`
	XXX_unrecognized     []byte                     `json:"-"`
	XXX_sizecache        int32                      `json:"-"`
}

func (m *MessageFindResponse) Reset()         { *m = MessageFindResponse{} }
func (m *MessageFindResponse) String() string { return proto.CompactTextString(m) }
func (*MessageFindResponse) ProtoMessage()    {}
func (*MessageFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{4}
}

func (m *MessageFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageFindResponse.Unmarshal(m, b)
}
func (m *MessageFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageFindResponse.Marshal(b, m, deterministic)
}
func (m *MessageFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageFindResponse.Merge(m, src)
}
func (m *MessageFindResponse) XXX_Size() int {
	return xxx_messageInfo_MessageFindResponse.Size(m)
}
func (m *MessageFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageFindResponse proto.InternalMessageInfo

func (m *MessageFindResponse) GetStatus() MessageFindResponse_Status {
	if m != nil {
		return m.Status
	}
	return MessageFindResponse_UNKNOWN
}

func (m *MessageFindResponse) GetFromUser() int32 {
	if m != nil {
		return m.FromUser
	}
	return 0
}

func (m *MessageFindResponse) GetToUser() int32 {
	if m != nil {
		return m.ToUser
	}
	return 0
}

func (m *MessageFindResponse) GetBadge() int32 {
	if m != nil {
		return m.Badge
	}
	return 0
}

func (m *MessageFindResponse) GetInfos() []*MessageInfo {
	if m != nil {
		return m.Infos
	}
	return nil
}

type NewMessage struct {
	FromUser             int32        `protobuf:"varint,1,opt,name=fromUser,proto3" json:"fromUser,omitempty"`
	ToUser               int32        `protobuf:"varint,2,opt,name=toUser,proto3" json:"toUser,omitempty"`
	Badge                int32        `protobuf:"varint,3,opt,name=badge,proto3" json:"badge,omitempty"`
	Info                 *MessageInfo `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *NewMessage) Reset()         { *m = NewMessage{} }
func (m *NewMessage) String() string { return proto.CompactTextString(m) }
func (*NewMessage) ProtoMessage()    {}
func (*NewMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{5}
}

func (m *NewMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewMessage.Unmarshal(m, b)
}
func (m *NewMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewMessage.Marshal(b, m, deterministic)
}
func (m *NewMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewMessage.Merge(m, src)
}
func (m *NewMessage) XXX_Size() int {
	return xxx_messageInfo_NewMessage.Size(m)
}
func (m *NewMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_NewMessage.DiscardUnknown(m)
}

var xxx_messageInfo_NewMessage proto.InternalMessageInfo

func (m *NewMessage) GetFromUser() int32 {
	if m != nil {
		return m.FromUser
	}
	return 0
}

func (m *NewMessage) GetToUser() int32 {
	if m != nil {
		return m.ToUser
	}
	return 0
}

func (m *NewMessage) GetBadge() int32 {
	if m != nil {
		return m.Badge
	}
	return 0
}

func (m *NewMessage) GetInfo() *MessageInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

type MessageQueryRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	OldMsg               bool     `protobuf:"varint,2,opt,name=oldMsg,proto3" json:"oldMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageQueryRequest) Reset()         { *m = MessageQueryRequest{} }
func (m *MessageQueryRequest) String() string { return proto.CompactTextString(m) }
func (*MessageQueryRequest) ProtoMessage()    {}
func (*MessageQueryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{6}
}

func (m *MessageQueryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageQueryRequest.Unmarshal(m, b)
}
func (m *MessageQueryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageQueryRequest.Marshal(b, m, deterministic)
}
func (m *MessageQueryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageQueryRequest.Merge(m, src)
}
func (m *MessageQueryRequest) XXX_Size() int {
	return xxx_messageInfo_MessageQueryRequest.Size(m)
}
func (m *MessageQueryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageQueryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MessageQueryRequest proto.InternalMessageInfo

func (m *MessageQueryRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *MessageQueryRequest) GetOldMsg() bool {
	if m != nil {
		return m.OldMsg
	}
	return false
}

type MessageQueryResponse struct {
	Status               MessageQueryResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=MessageQueryResponse_Status" json:"status,omitempty"`
	News                 []*NewMessage               `protobuf:"bytes,2,rep,name=news,proto3" json:"news,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *MessageQueryResponse) Reset()         { *m = MessageQueryResponse{} }
func (m *MessageQueryResponse) String() string { return proto.CompactTextString(m) }
func (*MessageQueryResponse) ProtoMessage()    {}
func (*MessageQueryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{7}
}

func (m *MessageQueryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageQueryResponse.Unmarshal(m, b)
}
func (m *MessageQueryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageQueryResponse.Marshal(b, m, deterministic)
}
func (m *MessageQueryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageQueryResponse.Merge(m, src)
}
func (m *MessageQueryResponse) XXX_Size() int {
	return xxx_messageInfo_MessageQueryResponse.Size(m)
}
func (m *MessageQueryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageQueryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MessageQueryResponse proto.InternalMessageInfo

func (m *MessageQueryResponse) GetStatus() MessageQueryResponse_Status {
	if m != nil {
		return m.Status
	}
	return MessageQueryResponse_UNKNOWN
}

func (m *MessageQueryResponse) GetNews() []*NewMessage {
	if m != nil {
		return m.News
	}
	return nil
}

func init() {
	proto.RegisterEnum("Type", Type_name, Type_value)
	proto.RegisterEnum("MessageCreateResponse_Status", MessageCreateResponse_Status_name, MessageCreateResponse_Status_value)
	proto.RegisterEnum("MessageFindRequest_Way", MessageFindRequest_Way_name, MessageFindRequest_Way_value)
	proto.RegisterEnum("MessageFindResponse_Status", MessageFindResponse_Status_name, MessageFindResponse_Status_value)
	proto.RegisterEnum("MessageQueryResponse_Status", MessageQueryResponse_Status_name, MessageQueryResponse_Status_value)
	proto.RegisterType((*MessageInfo)(nil), "MessageInfo")
	proto.RegisterType((*MessageCreateRequest)(nil), "MessageCreateRequest")
	proto.RegisterType((*MessageCreateResponse)(nil), "MessageCreateResponse")
	proto.RegisterType((*MessageFindRequest)(nil), "MessageFindRequest")
	proto.RegisterType((*MessageFindResponse)(nil), "MessageFindResponse")
	proto.RegisterType((*NewMessage)(nil), "NewMessage")
	proto.RegisterType((*MessageQueryRequest)(nil), "MessageQueryRequest")
	proto.RegisterType((*MessageQueryResponse)(nil), "MessageQueryResponse")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 627 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0x5f, 0x6f, 0xd3, 0x3e,
	0x14, 0xfd, 0x39, 0x7f, 0xba, 0xed, 0xb6, 0x9d, 0x22, 0xaf, 0xdb, 0x2f, 0x14, 0x10, 0x95, 0x9f,
	0x0a, 0x0f, 0x96, 0xd6, 0x6d, 0xe2, 0x0d, 0xa9, 0x6a, 0x03, 0x44, 0xd0, 0xae, 0x38, 0xed, 0xc6,
	0x9e, 0xa6, 0x4c, 0x75, 0xab, 0x4a, 0x6b, 0x52, 0xe2, 0x54, 0x25, 0x6f, 0x7c, 0x14, 0xde, 0x11,
	0xdf, 0x86, 0x0f, 0xc3, 0x1b, 0x28, 0x8e, 0x5b, 0xd6, 0x10, 0x24, 0xc4, 0xfa, 0x94, 0xe3, 0x7b,
	0x7a, 0x7d, 0x7c, 0x8e, 0xaf, 0xa1, 0x3a, 0xe7, 0x42, 0xf8, 0x53, 0x4e, 0x17, 0x51, 0x18, 0x87,
	0xe4, 0x13, 0x82, 0x72, 0x2f, 0x5b, 0x71, 0x83, 0x49, 0x88, 0x31, 0x18, 0xf1, 0x6c, 0xce, 0x6d,
	0xd4, 0x40, 0x4d, 0x9d, 0xc9, 0x6f, 0x6c, 0xc3, 0xce, 0x24, 0x8c, 0x56, 0x7e, 0x34, 0xb6, 0xb5,
	0x06, 0x6a, 0xee, 0xb2, 0x35, 0xc4, 0x0f, 0xc0, 0x88, 0x93, 0x05, 0xb7, 0xf5, 0x06, 0x6a, 0xee,
	0xb7, 0x4c, 0x3a, 0x4c, 0x16, 0x9c, 0xc9, 0x25, 0x6c, 0x81, 0x3e, 0x17, 0x53, 0xdb, 0x68, 0xa0,
	0xe6, 0x1e, 0x4b, 0x3f, 0xf1, 0x11, 0x94, 0x96, 0x41, 0xc4, 0xfd, 0xb1, 0x6d, 0xca, 0x2e, 0x0a,
	0x91, 0x15, 0xd4, 0x94, 0x82, 0x4e, 0xc4, 0xfd, 0x98, 0x33, 0xfe, 0x61, 0xc9, 0x45, 0x8c, 0xeb,
	0xb0, 0x3b, 0x89, 0xc2, 0xf9, 0x48, 0xf0, 0x48, 0xca, 0x31, 0xd9, 0x06, 0xa7, 0xbd, 0xe2, 0x50,
	0x56, 0x34, 0x59, 0x51, 0xe8, 0x2f, 0x05, 0x55, 0xa4, 0x20, 0xf2, 0x19, 0xc1, 0x61, 0x6e, 0x67,
	0xb1, 0x08, 0x03, 0xc1, 0xf1, 0x19, 0x94, 0x44, 0xec, 0xc7, 0x4b, 0x21, 0x37, 0xde, 0x6f, 0x3d,
	0xa6, 0x85, 0x3c, 0xea, 0x49, 0x12, 0x53, 0x64, 0x32, 0x80, 0x52, 0xb6, 0x82, 0xcb, 0xb0, 0x33,
	0xea, 0xbf, 0xe9, 0x9f, 0x5f, 0xf6, 0xad, 0xff, 0x70, 0x1d, 0xaa, 0x6e, 0xff, 0xa2, 0xfd, 0xd6,
	0xed, 0x5e, 0x0f, 0xda, 0xac, 0xdd, 0xb3, 0x7e, 0xac, 0x7f, 0x28, 0x25, 0x7a, 0xa3, 0x4e, 0xc7,
	0xf1, 0x3c, 0x0b, 0x61, 0x0b, 0x2a, 0x6b, 0xe2, 0xf0, 0x6a, 0xe0, 0x58, 0x1a, 0xf9, 0x86, 0x00,
	0xab, 0xad, 0x5f, 0xce, 0x82, 0xf1, 0x7d, 0xac, 0x79, 0x0a, 0xfa, 0xca, 0x4f, 0x94, 0x33, 0xff,
	0xd3, 0xdf, 0xbb, 0xd2, 0x4b, 0x3f, 0x61, 0x29, 0x07, 0xd7, 0xc0, 0xbc, 0x9d, 0xcd, 0x67, 0xb1,
	0x34, 0xab, 0xca, 0x32, 0x90, 0x36, 0x0e, 0x27, 0x13, 0xc1, 0x63, 0x99, 0x5f, 0x95, 0x29, 0x44,
	0x8e, 0x41, 0xbf, 0xf4, 0x93, 0xed, 0x23, 0x5b, 0x50, 0x61, 0x4e, 0xbb, 0x7b, 0xdd, 0x73, 0x3c,
	0xaf, 0xfd, 0xca, 0xb1, 0xe4, 0x41, 0x5f, 0xbb, 0xde, 0xf0, 0x9c, 0x5d, 0x59, 0x1a, 0xf9, 0x8e,
	0xe0, 0x60, 0x4b, 0x80, 0xf2, 0xfd, 0x24, 0xe7, 0xfb, 0x43, 0x5a, 0xc0, 0xca, 0xb9, 0xbe, 0x65,
	0x86, 0xf6, 0x47, 0x33, 0xf4, 0x2d, 0x33, 0x6a, 0x60, 0xde, 0xf8, 0xe3, 0x29, 0x97, 0x27, 0x34,
	0x59, 0x06, 0x30, 0x01, 0x73, 0x16, 0x4c, 0x42, 0x61, 0x9b, 0x0d, 0xbd, 0x59, 0x6e, 0x55, 0xe8,
	0x9d, 0xc9, 0x60, 0x59, 0x89, 0xbc, 0xb8, 0x5f, 0xc6, 0xe4, 0x23, 0x40, 0x9f, 0xaf, 0x54, 0xe3,
	0x7f, 0x0a, 0x72, 0xa3, 0x5d, 0xbf, 0xab, 0xbd, 0x01, 0x46, 0x2a, 0x50, 0x1e, 0x28, 0x2f, 0x5d,
	0x56, 0x88, 0xb3, 0xf1, 0xfc, 0xdd, 0x92, 0x47, 0xc9, 0xfa, 0x2e, 0xa5, 0x63, 0x29, 0x78, 0xe4,
	0x76, 0x95, 0x00, 0x85, 0x64, 0xdc, 0xb7, 0xe3, 0x9e, 0x98, 0xaa, 0xa1, 0x57, 0x88, 0x7c, 0x45,
	0x9b, 0x79, 0x55, 0x7d, 0x54, 0x78, 0xa7, 0xb9, 0xf0, 0x1e, 0xd1, 0x22, 0x5a, 0x3e, 0xbd, 0x27,
	0x60, 0x04, 0x7c, 0x25, 0x6c, 0x4d, 0x5a, 0x5e, 0xa6, 0xbf, 0xcc, 0x61, 0xb2, 0x70, 0x5f, 0xc3,
	0x9f, 0x9d, 0x81, 0x91, 0xbe, 0x02, 0xdb, 0xff, 0xde, 0x05, 0x63, 0xe8, 0xbc, 0x1f, 0x66, 0xf7,
	0x72, 0xe0, 0x76, 0x86, 0x23, 0xe6, 0x58, 0x1a, 0xde, 0x03, 0xf3, 0xc2, 0xed, 0x3a, 0xe7, 0x96,
	0xde, 0xfa, 0x82, 0x60, 0x67, 0x9d, 0xd2, 0x73, 0x28, 0x65, 0x83, 0x8f, 0x0f, 0x69, 0xd1, 0x53,
	0x55, 0x3f, 0x2a, 0x7e, 0x1f, 0xf0, 0x31, 0x18, 0xe9, 0xcd, 0xc5, 0x07, 0x05, 0xe3, 0x56, 0xaf,
	0x15, 0x5d, 0x6e, 0x7c, 0x0a, 0xa6, 0xf4, 0x0b, 0xd7, 0x68, 0x41, 0x5a, 0xf5, 0xc3, 0x42, 0x53,
	0x6f, 0x4a, 0xf2, 0x35, 0x3f, 0xf9, 0x19, 0x00, 0x00, 0xff, 0xff, 0x83, 0x67, 0x2c, 0x32, 0xde,
	0x05, 0x00, 0x00,
}
