// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: avatar.proto

package avatar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Avatar service

type AvatarService interface {
	Create(ctx context.Context, in *AvatarCreateRequest, opts ...client.CallOption) (*AvatarCreateResponse, error)
}

type avatarService struct {
	c    client.Client
	name string
}

func NewAvatarService(name string, c client.Client) AvatarService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "avatar"
	}
	return &avatarService{
		c:    c,
		name: name,
	}
}

func (c *avatarService) Create(ctx context.Context, in *AvatarCreateRequest, opts ...client.CallOption) (*AvatarCreateResponse, error) {
	req := c.c.NewRequest(c.name, "Avatar.Create", in)
	out := new(AvatarCreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Avatar service

type AvatarHandler interface {
	Create(context.Context, *AvatarCreateRequest, *AvatarCreateResponse) error
}

func RegisterAvatarHandler(s server.Server, hdlr AvatarHandler, opts ...server.HandlerOption) error {
	type avatar interface {
		Create(ctx context.Context, in *AvatarCreateRequest, out *AvatarCreateResponse) error
	}
	type Avatar struct {
		avatar
	}
	h := &avatarHandler{hdlr}
	return s.Handle(s.NewHandler(&Avatar{h}, opts...))
}

type avatarHandler struct {
	AvatarHandler
}

func (h *avatarHandler) Create(ctx context.Context, in *AvatarCreateRequest, out *AvatarCreateResponse) error {
	return h.AvatarHandler.Create(ctx, in, out)
}
