// Code generated by protoc-gen-go. DO NOT EDIT.
// source: avatar.proto

package avatar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AvatarCreateResponse_Status int32

const (
	AvatarCreateResponse_UNKNOWN       AvatarCreateResponse_Status = 0
	AvatarCreateResponse_INVALID_PARAM AvatarCreateResponse_Status = -1
	AvatarCreateResponse_SUCCESS       AvatarCreateResponse_Status = 1
	AvatarCreateResponse_INVALID_TYPE  AvatarCreateResponse_Status = 2
)

var AvatarCreateResponse_Status_name = map[int32]string{
	0:  "UNKNOWN",
	-1: "INVALID_PARAM",
	1:  "SUCCESS",
	2:  "INVALID_TYPE",
}

var AvatarCreateResponse_Status_value = map[string]int32{
	"UNKNOWN":       0,
	"INVALID_PARAM": -1,
	"SUCCESS":       1,
	"INVALID_TYPE":  2,
}

func (x AvatarCreateResponse_Status) String() string {
	return proto.EnumName(AvatarCreateResponse_Status_name, int32(x))
}

func (AvatarCreateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_082ad687f88f08fc, []int{1, 0}
}

type AvatarCreateRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	File                 []byte   `protobuf:"bytes,2,opt,name=file,proto3" json:"file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AvatarCreateRequest) Reset()         { *m = AvatarCreateRequest{} }
func (m *AvatarCreateRequest) String() string { return proto.CompactTextString(m) }
func (*AvatarCreateRequest) ProtoMessage()    {}
func (*AvatarCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_082ad687f88f08fc, []int{0}
}

func (m *AvatarCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarCreateRequest.Unmarshal(m, b)
}
func (m *AvatarCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarCreateRequest.Marshal(b, m, deterministic)
}
func (m *AvatarCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarCreateRequest.Merge(m, src)
}
func (m *AvatarCreateRequest) XXX_Size() int {
	return xxx_messageInfo_AvatarCreateRequest.Size(m)
}
func (m *AvatarCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarCreateRequest proto.InternalMessageInfo

func (m *AvatarCreateRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *AvatarCreateRequest) GetFile() []byte {
	if m != nil {
		return m.File
	}
	return nil
}

type AvatarCreateResponse struct {
	Status               AvatarCreateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=AvatarCreateResponse_Status" json:"status,omitempty"`
	AvatarID             string                      `protobuf:"bytes,2,opt,name=avatarID,proto3" json:"avatarID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *AvatarCreateResponse) Reset()         { *m = AvatarCreateResponse{} }
func (m *AvatarCreateResponse) String() string { return proto.CompactTextString(m) }
func (*AvatarCreateResponse) ProtoMessage()    {}
func (*AvatarCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_082ad687f88f08fc, []int{1}
}

func (m *AvatarCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AvatarCreateResponse.Unmarshal(m, b)
}
func (m *AvatarCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AvatarCreateResponse.Marshal(b, m, deterministic)
}
func (m *AvatarCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AvatarCreateResponse.Merge(m, src)
}
func (m *AvatarCreateResponse) XXX_Size() int {
	return xxx_messageInfo_AvatarCreateResponse.Size(m)
}
func (m *AvatarCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AvatarCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AvatarCreateResponse proto.InternalMessageInfo

func (m *AvatarCreateResponse) GetStatus() AvatarCreateResponse_Status {
	if m != nil {
		return m.Status
	}
	return AvatarCreateResponse_UNKNOWN
}

func (m *AvatarCreateResponse) GetAvatarID() string {
	if m != nil {
		return m.AvatarID
	}
	return ""
}

func init() {
	proto.RegisterEnum("AvatarCreateResponse_Status", AvatarCreateResponse_Status_name, AvatarCreateResponse_Status_value)
	proto.RegisterType((*AvatarCreateRequest)(nil), "AvatarCreateRequest")
	proto.RegisterType((*AvatarCreateResponse)(nil), "AvatarCreateResponse")
}

func init() { proto.RegisterFile("avatar.proto", fileDescriptor_082ad687f88f08fc) }

var fileDescriptor_082ad687f88f08fc = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2c, 0x4b, 0x2c,
	0x49, 0x2c, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x72, 0xe4, 0x12, 0x76, 0x04, 0xf3, 0x9d,
	0x8b, 0x52, 0x13, 0x4b, 0x52, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xc4, 0xb8, 0xd8,
	0x4a, 0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0x24, 0x18, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c, 0x21,
	0x21, 0x2e, 0x96, 0xb4, 0xcc, 0x9c, 0x54, 0x09, 0x26, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0x5b,
	0x69, 0x17, 0x23, 0x97, 0x08, 0xaa, 0x19, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x42, 0x26, 0x5c,
	0x6c, 0xc5, 0x25, 0x89, 0x25, 0xa5, 0xc5, 0x60, 0x43, 0xf8, 0x8c, 0x64, 0xf4, 0xb0, 0x29, 0xd3,
	0x0b, 0x06, 0xab, 0x09, 0x82, 0xaa, 0x15, 0x92, 0xe2, 0xe2, 0x80, 0xb8, 0xd0, 0xd3, 0x05, 0x6c,
	0x0d, 0x67, 0x10, 0x9c, 0xaf, 0x14, 0xc0, 0xc5, 0x06, 0x51, 0x2d, 0xc4, 0xcd, 0xc5, 0x1e, 0xea,
	0xe7, 0xed, 0xe7, 0x1f, 0xee, 0x27, 0xc0, 0x20, 0x24, 0xc5, 0xc5, 0xeb, 0xe9, 0x17, 0xe6, 0xe8,
	0xe3, 0xe9, 0x12, 0x1f, 0xe0, 0x18, 0xe4, 0xe8, 0x2b, 0xf0, 0x1f, 0x06, 0x18, 0x41, 0x0a, 0x83,
	0x43, 0x9d, 0x9d, 0x5d, 0x83, 0x83, 0x05, 0x18, 0x85, 0x04, 0xb8, 0x78, 0x60, 0x0a, 0x43, 0x22,
	0x03, 0x5c, 0x05, 0x98, 0x8c, 0xec, 0xb9, 0xd8, 0x20, 0x8e, 0x12, 0x32, 0xe5, 0x62, 0x83, 0x38,
	0x4c, 0x48, 0x44, 0x0f, 0x4b, 0x90, 0x48, 0x89, 0x62, 0x75, 0x7d, 0x12, 0x1b, 0x38, 0x1c, 0x8d,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x31, 0x87, 0x8e, 0xe7, 0x57, 0x01, 0x00, 0x00,
}
